### ISSUE TITLE
Event management for layers and map

### ISSUE THREAD

**Issue by claustres** [tombatossals/angular-openlayers-directive#100]
I noticed that event management for dedicated layers is not right. Actually, in the setVectorLayerEvents() function the layer name is passed as an argument but there is no filter on the retrieved features to check if they are from the given layer. This means that the event is raised even on features that does not belong to the layer.

I also noticed that only the 'pointermove' and 'singleclick' although the code is generic for any event type, I am working on a pull request for this.

**Comment by tombatossals** [comment]
Thanks so much for this useful functionality @claustres, I'm going to close this issue.
