### ISSUE TITLE
Heatmap inline definition

### ISSUE THREAD

**Issue by joydragon** [tombatossals/angular-openlayers-directive#104]
Hi, I'm using this directive and it's really fun for displaying data on a map but I'm having a problem.
Is there a way to generate a Heatmap without using a KML file?
I want to generate dinamically a heatmap but on the examples there's only the KML version, and the only "inline" one is the one with a GeoJSON source type.
Can you help me with that?

**Comment by tombatossals** [comment]
Yes of course, I only coded the basic examples on the directive, but we can code new funcionality. Can you provide an example of the provided format the data of your heatmap?

**Comment by Pedrazl** [comment]
Is it possible to see an example of a Heatmap based con GeoJSON features. With the new version I don´t find a way around....

**Comment by Pedrazl** [comment]
Just in case this could help someone, here is how I've done a Heatmap with dynamic GeoJson.
```javascript
/// Layer definition
{
                name: 'LayerName',
                opacity: 1,
                active: false,
                type: 'Heatmap',
                source: {
                    type: 'GeoJSON',
                    geojson: {
                        object: {
                        },
                        projection: 'EPSG:4326'
                    },
                    radius: 8,
                    blur: 15
                }
            }
.....
/// Dynamic load of geojson features on layer
layer.source.geojson.object = angular.copy(geoJson);
```
