### ISSUE TITLE
Making showOnMouseOver and showOnMouseClick work together

### ISSUE THREAD

**Issue by diazg** [tombatossals/angular-openlayers-directive#109]
Hi,

I've been playing around for the last weeks with you API and it's being really helpful. However, when adding some markers to my map, I would like to combine the 2 rendering strategies available.

This thing is that I want the user to see the overlay of a popup as soon as it is hovering it, but also to be able to hover the overlay itself, because I will be adding some HTML inside with a clickable link. 

For that reason, I extended your API a bit to show a marker's overlay until the users enters the mouse in other marker, when the overlay is changed to display the new marker's info. With this new behaviour an overlay is always visible unless the user clicks on a free marker zone of the map, which forces the visible overlay to close itself.

You can see all I am talking about in this plunker:
http://embed.plnkr.co/UrnVms4wIEJEB7WfXnfB/

If you find it useful, we can make it to the API.

Cheers!

**Comment by tombatossals** [comment]
Hi @diazg , sorry for the delayed response. That funcionality is great! It would be fantastic to add it to the actual code. If you could send a pull request I will merge it into the master.

Thanks

**Comment by diazg** [comment]
Hi @tombatossals,

Great to hear from you. Please, find my PR here:

https://github.com/diazg/angular-openlayers-directive/pull/1

Regards.

**Comment by mfilotto** [comment]
Hi,
Indeed, it would be very helpfull to have this kind of feature, to be able to click on a button inside the overlay.
But I wonder if it would not be more natural to keep the overlay open as long as the user hovers it.
What do you think ? Would not be possible ?

**Comment by cesardiaz** [comment]
Hi @mfilotto,

What you are saying makes sense, but don't you think both options can live together? In the app I am working on I personally prefer to have the behaviour I have already implemented, but I agree that sometimes what you said can be very useful as well. Why do we have to make a choice if we can have both? :P

**Comment by mfilotto** [comment]
Agreed, if we have to choose, let's take both ;)
And yours is already implemented by the way

**Comment by diazg** [comment]
PR opened here:

https://github.com/tombatossals/angular-openlayers-directive/pull/135
