### ISSUE TITLE
Redrawing a Geo JSON layer

### ISSUE THREAD

**Issue by dan-hook** [tombatossals/angular-openlayers-directive#111]
I'm creating a Geo JSON layer, and I update ctrl.clusterDisplayProperties by firing off a GET request to a server every time the extent of the map changes.  I can see the request hit the server, and I can see clusterDisplayProperites update.  Unfortunately, I never see the features on the map change.  How can I get the layer to update?

    <openlayers ol-center="ctrl.boundingBox" width="100%" height="100%">
        <ol-control name="{{ control.name }}" ng-repeat="control in ctrl.controls"></ol-control>
        <ol-layer ol-layer-properties="ctrl.clusterDisplayProperties"></ol-layer>
    </openlayers>

**Comment by mikostn** [comment]
faced similar problem... I've done it by "redrawing" layer directly in OL3

```
// create layer, see http://tombatossals.github.io/angular-openlayers-directive/#/layers/layer-geojson-inline
$scope.featuresLayer = {
    name: 'featuresLayer',
    source: {
        type: 'GeoJSON',
        geojson: {
            object: $scope.featuresGEOJSON,
            projection: 'EPSG:3857'
        }
   },
   style:(function () {
       ...
   })
}

...

//update on change
olData.getMap().then(function (map) {
    var layers = map.getLayers();
    layers.forEach(function (layer) {
        if (layer.get('name') === 'featuresLayer') {
            var lSource = layer.getSource();
            var nf = lSource.readFeatures($scope.featuresGEOJSON); //new features
            lSource.clear(); //remove existing features
            lSource.addFeatures(nf);
            layer.setStyle($scope.featuresLayer.style);
        }
    });
});
```

**Comment by dan-hook** [comment]
I've got it working now.  Thanks!

**Comment by mikostn** [comment]
no problem!
