### ISSUE TITLE
Add single marker on mouse click

### ISSUE THREAD

**Issue by mahmoudmy** [tombatossals/angular-openlayers-directive#113]
I saw you add a nice example for adding marker on mouse click events. You used a markers object and push new marker positions by every click to it. I need to add just one marker to my map by click. It means if the user click again after showing a marker, the previous marker disappears and a new marker comes to map. How can I do this?

**Comment by tombatossals** [comment]
That should be easy, you on need to clear the "markers" array and mantain only one marker inside it. When the click event is received, clean the array and add the item.
