### ISSUE TITLE
Markers error

### ISSUE THREAD

**Issue by jpablom** [tombatossals/angular-openlayers-directive#116]
Hi guys, hope anyone help me with this:

I'm trying to add some markers to my map, but throws me error:
`RangeError: Maximum call stack size exceeded at Function.getOwnPropertyNames (native)`
This happens since i updated angular-openlayers-directive to v0.0.5 because i need handle click event on markers.

my code:
```javascript
$scope.markers = [
    {
        lat: 20.679,
        lon: -103.386,
        onClick: function (){
            console.log('click');
        }
    }
]
```
template

```html
<openlayers ol-center="center" width="100%" height="94vh">
    <ol-marker ng-repeat="marker in markers" ol-marker-properties="marker"></ol-marker>
</openlayers>
```

thanks!

**Comment by fungur** [comment]
I'm having the same issue. Can't add any markers.
Any workaround?

**Comment by tombatossals** [comment]
Please, can you provide a jsfiddle showing this behaviour? You can start from this fiddle:
http://jsfiddle.net/tombatossals/v3b0p54h/

**Comment by BenSower** [comment]
I have the same problem, but I cannot reproduce it using the jsfiddle. Mainly I think this happens since I am using jade instead of standard html. I will try to check if everything works fine in html.

**Comment by BenSower** [comment]
Ok, last post for today. I "fixed the problem" by upgrading from openlayers 3.0.0 to openlayers 3.4.0. 
How I feel after chasing down the wrong rabbit hole for 90 minutes: 
![FML...](http://d24w6bsrhbeh9d.cloudfront.net/photo/a9dKbym_460sa.gif)
