### ISSUE TITLE
Problem with maker label defaults

### ISSUE THREAD

**Issue by mahmoudmy** [tombatossals/angular-openlayers-directive#118]
I need to show marker labels just by "mouse over" event by default and because the markers data are too much, it's not possible to set the  `show: false` and `showByMouseOver: true` in the controller's $scope and also there is not related attribute in `ol-marker` tag, so I changed these values in *angular-openlayers-directive-js > olMarker directive > getMarkerDefaults function*, but there in no change in showing labels, all the labels appear on the map!! How is it?

**Comment by tombatossals** [comment]
Please, could you provide a jsfiddle or plunker showing this behaviour?

**Comment by claustres** [comment]
Moreover what do you mean exactly by *the markers data are too much* ?

**Comment by notph** [comment]
I've trie to change the angular-openlayers-directives.js but it's still not working.

Lines 697 to 708
`
    var getMarkerDefaults = function() {
        return {
            projection: 'EPSG:4326',
            lat: 0,
            lon: 0,
            coord: [],
            **show: false,
            showOnMouseOver: true,
            showOnMouseClick: false,
            keepOneOverlayVisible: false**
        };
    };`

**Comment by juristr** [comment]
@notph Can you try with our latest version if the problem persists? In case please re-open this issue, thx.
