### ISSUE TITLE
GeoJSON with Style?

### ISSUE THREAD

**Issue by juristr** [tombatossals/angular-openlayers-directive#123]
Hi,

I am not sure if I just missed it somewhere from the docs, but is it possible to register a GeoJSON layer with a specific style?

Currently I can do something like

```javascript
{
  source: {
    type: 'GeoJSON',
    geojson: {
      object: {...}
    }
  }
}
```

and register it with the angular-openlayers-directive. Is it possible to specify a style with this layer as well? Similar to what this ol3 code example does: https://astuntechnology.github.io/osgis-ol3-leaflet/ol3/02-GEOJSON.html

Unfortunately, at the moment I have to do it like this:

```
olData.getMap().then(function(map) {
  var layers = map.getLayers();

  layers.forEach(function(layer) {
    if (layer.get('name') === TEMPORARY_LAYER_NAME) {
      var source = layer.getSource();

     ...

      layer.setStyle(new ol.style.Style({
          // this should be doable through the openlayers directive somehow...
          // for now it's simply a copy of its style
          image: new ol.style.Icon({
                anchor: [0.5, 1],
                anchorXUnits: 'fraction',
                anchorYUnits: 'fraction',
                opacity: 0.90,
                src: base64icon
          })
      }));
    }
  });
});
```

**Comment by milafrerichs** [comment]
Yes, should be doable. I think I tried it before but not sure.
Have a look here:
https://github.com/tombatossals/angular-openlayers-directive/blob/master/examples/050-layer-geojson-change-style-example.html#L23

Try adding:
```js
{
  source: {
    type: 'GeoJSON',
    geojson: {
      object: {...}
    },
    style: {
      image: {
        ....
      }
    }
  }
}
```

**Comment by kitab15** [comment]
I'm trying something like that:

```javascript
source: {
    type: 'GeoJSON',
    geojson: {
        object: {...},
    }
},
style: {
    fill: {
        color: '#FF0000'
    },
    stroke: {
        color: '#FFFFFF',
        width: 3
    }
}
```

and like @milafrerichs says in the previous post: (With the style block inside the source block)

```javascript
source: {
    type: 'GeoJSON',
    geojson: {
        object: {...},
    },
    style: {
       fill: {
        color: '#FF0000'
       },
       stroke: {
        color: '#FFFFFF',
        width: 3
      }
   },
}
```

But it's not working... Some idea?

**Comment by juristr** [comment]
Meanwhile I went ahead and created a fork of angular-openlayers-directive that works with ol3 > `v3.5`. I'm actually using `v3.6` at the moment: https://github.com/juristr/angular-openlayers-directive/tree/v3.5.0

I [just pushed a commit on my fork](https://github.com/juristr/angular-openlayers-directive/commit/3a2490adbaa8ed72c14f2816ade083e0810031fa) that fixes the styling issue mentioned in this issue here. It permits to use the new openlayers v3.6 vector api with an eagerly loaded GeoJSON object (not just with the `url` property) and to pass according styles to be used with it:

```
var geoJsonLayer = {
  source: {
    type: 'GeoJSON',
    geojson: {
       object: {
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [
              11.3243,
              46.508745
            ]
          }
       },
       projection: '...'
    }
  },
  style: {
     ...
  }
}
```

I'm waiting for some input from @tombatossals on #120 in order to submit a PR and solve this issue. Once that PR is submitted and merged, this issue can be closed as well.

**Comment by Pedrazl** [comment]
I don´t know if you guys have the same issue, but when I inject the geojson object (on user interaction) I lose the layer style. If you use the 'url' property instead it works. 
Any idea?

**Comment by juristr** [comment]
@pedrazl which version of the directive are u using? If I recall correctly, I fixed this and I think it got released.

**Comment by Pedrazl** [comment]
Hi @juristr, thanks for your answer. 
I have the last version, 0.0.7. After some hours fighting against the style's strange behaviour I got a work around. 
I have a layer object with a predefined style declared on initialization:
```javascript
var layer = {
            source: {
                type: 'GeoJSON',
                geojson: {
                    projection: 'EPSG:3857',
                    object: {
                    }
                }
            },
            style: (function () {
                var layerStyle= function (r, c) {
                    return [new ol.style.Style({
                        image: new ol.style.Circle({
                            radius: r,
                            fill: new ol.style.Fill({
                                color: c
                            }),
                            stroke: new ol.style.Stroke({
                                color: '#A01806',
                                width: 2
                            })
                        })
                    })]
                };
                return function (feature, resolution) {
                    return layerStyle(feature.get('mw'), 'red');
                };
            }())
        }
```
Then, on user interact, I load data on this layer's geojson:
```javascript
layer.source.geojson.object = angular.copy(layerData);
```
At that point the features are drawn on the layer, but the style dissapear. I don´t know what happen, but looks like on geojson update, the layer reset his style.
The workaround I found is to apply manually the style every time I load geoson on layer:
```javascript
layer.style = angular.copy(layerStyle);
```
That works, but anyway it looks like a kind of bug.

**Comment by juristr** [comment]
Hmmm...I'll look into this. As far as I know, we also dynamically update yhe styles of our GeoJSON layer. Need to check how we do it there and whether I can reproduce the issue as well. I'll let u know.
Meanwhile, thx for reporting it :smiley:

**Comment by Pedrazl** [comment]
...just to be sure the version I am using is fine, my dependendy in Bower looks like that:
```javascript
"dependencies": {
        "angular": "1.3.15",
        "angular-resource": "1.3.15",
        "angular-openlayers-directive": "0.0.7",
        ......
```
I realize that the directive download openlayers3 (3.4) as dependency. Is that ok or is there another way to work against the last version of openlayers? Maybe the bower config is not taking last version as default...



I just realize that I am working against angular-openlayers-directive 0.0.7, and it download

**Comment by juristr** [comment]
Yes, v0.0.7 is the latest version. It currently references [openlayers v3.4 as dependency](https://github.com/tombatossals/angular-openlayers-directive/blob/master/bower.json#L17). You could simply reference a newer version of openlayers, however there's an issue from >= v3.5 as ol3 introduced some breaking changes. I'm working on bringing angular-openlayers-directive to v1.0.0 which will be compatible with ol3 > v3.5. See #155 for more details.

**Comment by Pedrazl** [comment]
Ah, ok, perfect then. Thanks for your effort @juristr!

**Comment by juristr** [comment]
Meanwhile..could you maybe send me a couple of lines of code that reproduce the issue...or a working plunkr that shows it would be awesome.

**Comment by Pedrazl** [comment]
Sure, I just need somo free time, I´ll let you know as soon as I have it reproduced on plunkr.

**Comment by juristr** [comment]
:thumbsup: great, thx

**Comment by Pedrazl** [comment]
Hi @juristr 
Here you are a working plunkr with the bug we talked about:
http://plnkr.co/edit/Djr53KYBsfyYROG8bNno?p=info

**Comment by Pedrazl** [comment]
@juristr did you see the plunker?

**Comment by juristr** [comment]
@Pedrazl Yep, sorry for not having answered. Unfortunately I didn't have time recently, not sure whether I'll make it till sunday evening 'cause then afterwards I'm in holiday and won't be able to contribute here.

I'll see what I can do.

**Comment by Pedrazl** [comment]
@juristr it was only to be sure you are able to see the plunker correctly. Don´t worry and enjoy your holidays
