### ISSUE TITLE
Map tiles skewed until page resize

### ISSUE THREAD

**Issue by beefo** [tombatossals/angular-openlayers-directive#125]
The map tiles are skewed on initial page load. Re-sizing the page clears it up. Is it possible to trigger map.updateSize on the directive?

http://i.imgur.com/ByKY2QN.gif

**Comment by juristr** [comment]
Hmm, I also once noticed this kind of behavior, but wasn't able to reproduce it reliably.

If you want to update the map, you can get a reference to the ol3 map object like this:

```javascript
// within some service, controller or directive, inject olData
module.factory('mapService', function(olData){
   ...
   olData.getMap().then(function(map) {
       // use the map object
       ...
   });
});

**Comment by beefo** [comment]
'mapService' couldn't be found when I tried to include it. Is it part of the angular-openlayers-directive?

I created a code pen to illustrate the issue: http://codepen.io/beefo/pen/doXMzr?editors=101
You can see that re-sizing the window after the content is loaded fixes the issue. Could be a side effect of using with angular-material.

**Comment by juristr** [comment]
No, `mapService` was just an example to illustrate the injection of `olData`, which is part of the angular-openlayers-directive.
Simply inject that one in your service, directive or controller and then call `olData.getMap()....` just as I did in the example before.

**Comment by beefo** [comment]
Ah, yes. I see now. Huge  help, thanks @juristr

**Comment by juristr** [comment]
+1 Could you close the issue if this solves your problem? thx
