### ISSUE TITLE
Style definition is lost when updating layer.

### ISSUE THREAD

**Issue by mfdev1** [tombatossals/angular-openlayers-directive#127]
Hi @tombatossals,

I want update object several times with ol-layer directive.
But style definition is lost when updating layer.

1. Assign GeoJSON layer to ol-layer with style.
2. Update source.geojson.object.
3. Then layer was updated, but style definition is lost!

Example:
http://plnkr.co/edit/P10agHojRk3ugyd66nss

olLayer.setStyle method it will not seem to have been executed when there is no change in style.
https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/directives/layer.js#L135

**Comment by mikostn** [comment]
maybe this would help
Redrawing a Geo JSON layer #111

**Comment by mfdev1** [comment]
Hi @mikostn ,

Thank you answer me!
But I think I'm sorry that approach is a little different.
When was it to put the newly created object to the style.

```javascript
$scope.layer.style = angular.copy(templateStyle);
```

But I hope that ol-layer is corrected.

**Comment by tombatossals** [comment]
Hi @mfdev1, you're totally right again. I have updated the library to preserve the style between layer source changes. Your plunker must work now, I have updated one of the examples to show this functionality:

http://tombatossals.github.io/angular-openlayers-directive/examples/055-layers-geojon-dynamic-load-example.html

Thanks for reporting.

**Comment by mfdev1** [comment]
Thank you!!
