### ISSUE TITLE
Move marker dynamically

### ISSUE THREAD

**Issue by tajikase** [tombatossals/angular-openlayers-directive#129]
Are there any ways to move (Change lon, lat) markers?

I put this in html.
```
<openlayers ol-defaults="defaults" ol-center="center">
    <ol-marker ol-marker-properties="marker"></ol-marker>
</openlayers>
```

And defined marker in the controller.
```
$scope.marker = {
    lon: 139.7,
    lat: 35.69
};
```

The marker was shown in the map correctly, but it could not be moved even I changed lon, lat variables after that.
```
$scope.marker.lon = 130;
$scope.marker.lat = 37;
```

**Comment by tombatossals** [comment]
Hi, you're totally right, this funcionality wasn't implemented. I have added the code to dinamically change the marker position from the scope properties of the marker. You can see a demo of it here:

http://tombatossals.github.io/angular-openlayers-directive/#/markers/marker-properties
