### ISSUE TITLE
Example nº 50 not working

### ISSUE THREAD

**Issue by avsilva** [tombatossals/angular-openlayers-directive#130]
Example nº 50 not working:

http://tombatossals.github.io/angular-openlayers-directive/examples/050-layer-geojson-change-style-example.html

The layer style doesn't change on user submited colors. I'm I doing something wrong?

tks.

**Comment by tombatossals** [comment]
Yess, this was caused by a recent PR which tried to optimize the deeper watcher of the layer properties. I have reverted the commit since we can think a better strategy for this. It's working again now.

**Comment by avsilva** [comment]
Thanks for your quick response.
