### ISSUE TITLE
The ol-marker Clearing not disappear div tag of popup

### ISSUE THREAD

**Issue by mfdev1** [tombatossals/angular-openlayers-directive#132]
Hi @tombatossals,

when you clear the ol−marker, it seems to remain div tag that you created in the pop-up.
Please check since the sample was prepared.
https://jsfiddle.net/mfdev1/48zujvdh/6/

div tag will continue to increase with each additional marker.

In destroy the timing , it may be necessary to clear the overlay.

**Comment by tombatossals** [comment]
You're totally right @mfdev1, thanks for reporting, I have solved it in the last commit
