### ISSUE TITLE
Draggable Markers

### ISSUE THREAD

**Issue by MrGorki** [tombatossals/angular-openlayers-directive#133]
Thanks for this brilliant work @tombatossals !!
Does this directive has also a feature to manage draggable markers? I mean, changing the js marker object when dragging on the map?

Thanks a lot!!!

**Comment by tombatossals** [comment]
Hi @MrGorki, not at this moment, it would be a useful feature, and feasible to implement. Maybe in the future we can get it.

**Comment by MrGorki** [comment]
Thank you!

**Comment by claustres** [comment]
Created PR for this : https://github.com/tombatossals/angular-openlayers-directive/pull/180
