### ISSUE TITLE
ol-controls not working for primitive controls like zoom and attribution

### ISSUE THREAD

**Issue by MrGorki** [tombatossals/angular-openlayers-directive#136]
Adding or removing those primitive controls has no effect even on the example:

http://tombatossals.github.io/angular-openlayers-directive/examples/100-controls-example.html

**Comment by mikostn** [comment]
heh, it seems that, it is working but not as expected, and only halfway...
every time You toggle control to true, new control instance is loaded.

**Comment by MrGorki** [comment]
Great to hear that it has been figured out! Thanks a lot!

**Comment by mikostn** [comment]
only partially, as toggling to false doesn't work, and I'm not sure what it's caused by.

**Comment by MrGorki** [comment]
I think this issue: https://github.com/tombatossals/angular-openlayers-directive/issues/139 is also coming from the same origin. It has some base settings to include these controls and layer

**Comment by MrGorki** [comment]
I did send a pull request to change the defaults: https://github.com/tombatossals/angular-openlayers-directive/pull/140

**Comment by mikostn** [comment]
@MrGorki, changing defaults in just a temporary solution. Problem is that once added control is not removed, when set false.

**Comment by mikostn** [comment]
it is probably related to my previous commit #126 - I'm looking for solution

**Comment by mikostn** [comment]
see PR #141 - You should be able to remove (custom) controls by setting false.
To override defaults, see example 100 (my PR)

```
angular.extend($scope, {
    defaults : {
        controls: {
            zoom: false,
            rotate: false,
            attribution: false
        }
    },
...
    controls: [
        { name: 'zoom', active: false },
        { name: 'rotate', active: false },
        { name: 'attribution', active: false }
    ]
...
});
```
html
```
<openlayers ol-center="center" ol-defaults="defaults" ol-controls="controls" ol-view="view">
   <ol-control name="{{ control.name }}" ng-repeat="control in controls|filter: {active: true}"></ol-control>
</openlayers>
```

**Comment by MrGorki** [comment]
@mikostn You are absolutely right! And now it works like a charm! Thanks!

**Comment by mikostn** [comment]
glad, I could help! ;)

**Comment by mikostn** [comment]
and I'd suggest reverting Your PR
