### ISSUE TITLE
Feature request: Invisible marker with label only

### ISSUE THREAD

**Issue by style-x7** [tombatossals/angular-openlayers-directive#137]
Hi @tombatossals , it's me again, the static map enthusiast.

I'd like to request for the above feature as it can be an useful feature, say I want to show the nearby point of interests and using the current markers, it gets a little too clustered. Will be great if I can set the markers to invisible and just showing the label.

Thanks in advance.

**Comment by claustres** [comment]
This is already possible, simply use a "void" style on your marker:
```javascript
var marker = {
    lat: xxx,
    lon: yyy,
    style: {}, // No style to display nothing except popup
    label: {
        message: 'hello !',
        show: true
    }
  };
```
worked for me...

**Comment by juristr** [comment]
@style-x7 Does @claustres solution match your needs? I'm closing this issue. In case feel free to comment and re-open it again. Thx
