### ISSUE TITLE
Zoom control doesn't seem to work when bind to button/input etc

### ISSUE THREAD

**Issue by kwektuanze** [tombatossals/angular-openlayers-directive#138]
Hi @tombatossals and everyone,

I'm using master version of the directive and working with static maps.

Tried the example http://tombatossals.github.io/angular-openlayers-directive/examples/023-center-constrain-zoom-example.html and changing the $scope.london.zoom programmatically doesn't seem to cause the zooming effect.

Can kindly assist?

**Comment by Pedrazl** [comment]
Hi @kwektuanze,
you shouldn´t have problem with that. In your map controller you can have something like this:
```javascript

var vm = this;

vm.center = {
                lat: 15,
                lon: 0,
                zoom: 1,
                bounds: []
                };
vm.centerMap = function(centerObject){
 vm.center = angular.copy(centerObject);
 }
```
Then you just have to bind the center object to your html directive this way:
```
<openlayers ol-center="mapController.centro" width="100%" height="430px">
```
With that code you should be able to call centerMap function  programmatically where you want.

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).
