### ISSUE TITLE
olPath at times not removed after clearing paths[] 

### ISSUE THREAD

**Issue by kwektuanze** [tombatossals/angular-openlayers-directive#144]
Hi tombatossals, 

I'm using path drawing from https://github.com/tombatossals/angular-openlayers-directive/blob/master/examples/110-path-example.html, which is really useful, thanks!

However, when I tries to clear paths ($scope.paths = []) dynamically, it doesn't clear. I have to transit to another view and come back to the view (with angular-openlayers) to clear paths. 

Not sure if olPath faces similar resolved marker issue: https://github.com/tombatossals/angular-openlayers-directive/issues/110. 

Will you (or someone knowledgeable) be able to look into it? I tried to edit the angular-openlayers-directive.js but not getting any good result.

**Comment by style-x7** [comment]
Hi there, 

Managed to find a possible solution ~

Under angular-openlayers-directive.js, find olPath directive. Just before the line "if (isDefined(attrs.coords))", add the following:
                scope.$on('$destroy', function() {
                    layer.getSource().removeFeature(feature);
                });

After which, you should be able to clear existing olPath.

Thanks to @zzats and #110. Hi @tombatossals, maybe you can test it out and commit into the codebase :)

**Comment by dvmac** [comment]
Hi there,
I don't know if anyone can help me but I'm trying to create a 'drawing function' that would allow users to create paths dynamically and I can get it to work using Openlayers 3 standard functionality but I don't seem to be able to get anything drawn using this directive at all. Any help would be greatly appreciated, Thanks.

**Comment by style-x7** [comment]
Hi @dvmac ,

I'll try to help out (I'm still a newbie). You can do something like:

    <openlayers ... >
      <ol-path ng-repeat="path in paths" proj="{{path.projection}}" coords="{{path.coord}}"></ol-path>
    </openlayers>

Then in your controller where you extend the $scope:

  angular.extend($scope, {
                  ... ,
                  **paths: []**
  });

When you want to create path dynamically:

    $scope.paths.push({
      projection: '<INSERT PROJECTION TYPE>',
      coord: [[<INSERT START COORD> ,<INSERT END COORD>]]
    });

**Comment by dvmac** [comment]
Thanks style-x7, I hadn't quite figured the coords="{{path.coord}}" part but that ties in with what I've been trying so far.

For the actual function itself, I've tried to adapt an existing markers control (which works) but I'm getting an SyntaxError: Unexpected end of input at Object.parse (native).

This is my function:
$scope.drawPath = function () {
        $scope.$on('openlayers.map.singleclick', function (event, data) {
            var prj = ol.proj.transform([data.coord[0], data.coord[1]], data.projection, 'EPSG:4326').map(function (c) {
                return c.toFixed(4);
            })
            $scope.$apply(function () {
                $scope.paths.push({
                    lat: data.coord[1],
                    lon: data.coord[0],
                    projection: data.projection,
                    label: {
                        message: "Lat: " + prj[1] + ", Lon: " + prj[0],
                        show: false,
                        showOnMouseOver: true
                    }
                });
            });
        });
    };

If you could shed any light I'd really appreciate it but thanks for your input.

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).
