### ISSUE TITLE
Create a vector layer to put some features in it on demand

### ISSUE THREAD

**Issue by danielrvt** [tombatossals/angular-openlayers-directive#145]
I'm having a lot of trouble. First, there is no examples on creating a vector layer that can hold some features. Anyone has any Idea?

**Comment by grzegorz-jazurek** [comment]
It's a little hacky way, but you can receive ol.Map object by executing olData.getMap method and use standard ol API.
Here is my sample code: http://jsfiddle.net/ahvj8mw0/14/

**Comment by penance316** [comment]
thats what i have had to do also. hopefully we can get a nicer way of drawing features soon. Thats the only thing missing that i currently need. I would be interested in adding the feature into the code but not sure where to start.

**Comment by juristr** [comment]
@penance316 @grzegorz-jazurek Maybe I can help you in guiding you to implement it.
What's the API you'd like to have. Any ideas already?

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).
