### ISSUE TITLE
Map Control visibility

### ISSUE THREAD

**Issue by dvmac** [tombatossals/angular-openlayers-directive#147]
Hi there,
I've been trying to incorporate some custom controls on a map as per this example:
http://tombatossals.github.io/angular-openlayers-directive/#/more/control

The controls appear to be loaded in the DOM but are not actually appearing onscreen. Ultimately I'd like to include a custom control called ol-layerswitcher but I can't even get the 'basic' controls to appear.

A plunkr would be too difficult to include but here is a link to a demo:
http://dev.rgsit.com/ux/xped2AngBuild/index.html

Thanks in advance for any help.

**Comment by claustres** [comment]
First you should add this to your `defaults` to avoid creating the default controls:
```javascript
angular.extend($scope, {
defaults : {
  controls: {
                    zoom: false,
                    rotate: false,
                    attribution: false
                }
},
...
```
Then you missed the really important `ol-control-properties` attribute on your control directive:
```html
<ol-control name="{{ control.name }}" ol-control-properties="control" ng-repeat="control in controls|filter: {active: true}"></ol-control>
```
This should work better although i cannot test on my side.

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).
