### ISSUE TITLE
Zoom to boundingbox 

### ISSUE THREAD

**Issue by YossiCohen** [tombatossals/angular-openlayers-directive#149]
I tried to figure out how to zoom the map to bounding box but could'nt find a good example.

Lets assume a Nominatim Search Service returns 
boundingbox: [
"32.0777918",
"32.0787494",
"34.7668651",
"34.7676123"
]

How can I set themap to zoom to the bounding box without complicate conversation of the 4 bounds to (center, zoom)?

**Comment by claustres** [comment]
You should probably have to do something like this to use such a functionality provided by OL3 (although not tested) :
```javascript
    ...
    olData.getMap().then(function(map) {
                // OL 3.4
                map.getView().fitExtent(extent, map.getSize());
                // OL 3.7
                //map.getView().fit(extent, map.getSize());
                // Reflect center/zoom in directive setup
                $scope.center.lon = map.getView().getCenter()[0];
                $scope.center.lat = map.getView().getCenter()[1];
                $scope.zoom = map.getView().getZoom();
              });
```

**Comment by juristr** [comment]
@YossiCohen @claustres Note that in the latest release of ol3 they changed `fitExtent` -> `fit`.
