### ISSUE TITLE
Current tests are failing

### ISSUE THREAD

**Issue by jengeb** [tombatossals/angular-openlayers-directive#152]
By the way do you plan do make a new release?

**Comment by juristr** [comment]
@jengeb `v0.0.6` has been released [3 days ago](https://github.com/tombatossals/angular-openlayers-directive/commit/6e68aa328b4f9227319ac3b8086312db3262705d).

We're currently planning to release v1.0.0 (#155) which will be compatible with ol > v3.5.

**Comment by jengeb** [comment]
@juristr Thanks for your reply and the info!

**Comment by juristr** [comment]
Just released v0.0.7 containing a minor bugfix when using the "text" style.
