### ISSUE TITLE
Update Strategy for openlayers > v3.5

### ISSUE THREAD

**Issue by juristr** [tombatossals/angular-openlayers-directive#155]
Hi,

I feel a bit dumb as I tried to ask for this in multiple other issues. So, trying again to bring this to the table :smile: .

Currently angular-openlayers-directive works with openlayers < v3.5. In ol `v3.5` there have been a couple of [breaking changes](https://github.com/openlayers/ol3/releases/tag/v3.5.0) due to the new Vector API that has been introduced. #120 already discusses this. Meanwhile v3.6 and v3.7 have been released. As you mentioned in #120, @tombatossals , you already started a branch v3.5 which does some initial steps in upgrading the code of angular-openlayers-directive to match the new Vector API.

I've taken your branch [and continued to work on it](https://github.com/juristr/angular-openlayers-directive/tree/v3.5.0) as I'm using angular-openlayers-directive with ol v3.6 (soon v3.7). I already merged in most of the bugfixes here on master plus some more changes.

What I'd like to discuss is on how to bring angular-openlayers-directive to the latest version that works with ol v3.6. I'm obviously willing to contribute my branch. 

We'd have to

- [x] Contribute back my v3.5 branch with fixes for the latest ol3 version
- [x] Release angular-openlayers-directive under version v1.0.0 as this is a breaking change for others using angular-openlayers-directive and to be compatible with [http://semver.org/](http://semver.org/) (which is absolutely suggested)

@tombatossals Please let me know how you think to proceed.

**Comment by tombatossals** [comment]
Hi @juristr, you're totally right. And I'm sorry for the lack of updates, I'm not actively using this directive, so I only work on it on my spare time, because I love openlayers and angular. :)

As you say, we need to bump the version of the directive to 1.x, because of the breaking changes. It would be great if you could PR your branch so we can merge it. From that time, I would start working on the 1.x branch, because we need to move in the OpenLayers direction.

One question, do you want developer grants on this repository? It would be great if you could share your progress directly on the repository.

Thanks for your help.

**Comment by juristr** [comment]
> It would be great if you could PR your branch so we can merge it. From that time, I would start working on the 1.x branch, because we need to move in the OpenLayers direction.

Definitely. I'll prepare a PR and submit it. Probably Sunday evening or Monday morning. We probably have to put down a couple of lines regarding the steps for upgrading to openlayers > v3.5. I'll think about that.

> One question, do you want developer grants on this repository? It would be great if you could share your progress directly on the repository.

Sure, I can see what I can do. Thanks a lot! Obviously I won't have that much time too, but at least I can share what I'm doing in the course of using this directive in our application. And maybe help with some issues as well. We will see :smiley:

**Comment by tombatossals** [comment]
That's fantastic! I add you to the repository then, if you have in mind tasks that would be interesting to work on, just tell me, I could start working in some of them.

**Comment by juristr** [comment]
@tombatossals I'm preparing the PR which I'll submit in the coming days. Btw, I've seen you occasionally use the conventional commit message style [just like Angular does](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit). What do you think of using [the semantic-release](https://github.com/semantic-release/semantic-release) for angular-openlayers-directive from `v1.0.` on?

I used it on one of my small [angular utility lib for angular-translate](https://github.com/juristr/angular-translate-loader-pluggable/releases) and it works great. Generates nice release logs for free as well.

**Comment by juristr** [comment]
Ok, `v1.0.0` released: https://github.com/tombatossals/angular-openlayers-directive/releases/tag/v1.0.0
Now official compatible with ol3 > v3.5
