### ISSUE TITLE
Control of setting the event to multiple layers (map and vector)

### ISSUE THREAD

**Issue by mfdev1** [tombatossals/angular-openlayers-directive#157]
Hi,

If you have set a click event to the map and the vector layer , it will also be firing map of events when you click on the feature of the vector.

Suppresses the event set in the map, Is it possible to fire only events set in the vector Layer ?

Please check since the sample was prepared.
http://jsfiddle.net/mfdev1/zgj6q6La/4/

**Comment by BenSower** [comment]
I am not quite sure if I understood you correctly, but I think you only want one event to be fired and not two different ones? So only the click on the map OR the click on the vector layer?

If so, I guess you could try fixing your fiddle by using the same event for both the map AND the layer:

```
        defaults: {
            events: {
                map: ['click'],
                layers: ['click']
            }
        }

[...]

    $scope.$on('openlayers.map.click', function (event, data) {
        $scope.$apply(function (scope) {
            $scope.mouseClickVector = '';
            if (data) {
                var p = ol.proj.transform([data.coord[0], data.coord[1]], data.projection, 'EPSG:4326');
                $scope.mouseClickMap = p[0] + ', ' + p[1];
            }
        });
    });
```

**Comment by mfdev1** [comment]
Hi @BenSower, thanks for your answer. 

But, it was not I wanted answers.

Any example that I received seems to be firing two events.

As for me, if the feature of the vector layer is selected, I want to know how you do not want to fire the events of the map layer.

It supports now be handled in a map of the event.
See http://jsfiddle.net/mfdev1/zgj6q6La/12/ for full example

please tell me if there is a smart way

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).
