### ISSUE TITLE
An error occurs. If you use the requirejs.

### ISSUE THREAD

**Issue by realrnjs** [tombatossals/angular-openlayers-directive#161]
An error occurs. If you use the requirejs (http://www.requirejs.org/)
error : ReferenceError: ol is not defined

thank you.

source

require.config({
paths: {
angular: '../../bower_components/angular/angular',
'angular-animate': '../../bower_components/angular-animate/angular-animate',
'angular-cookies': '../../bower_components/angular-cookies/angular-cookies',
'angular-mocks': '../../bower_components/angular-mocks/angular-mocks',
'angular-resource': '../../bower_components/angular-resource/angular-resource',
'angular-route': '../../bower_components/angular-route/angular-route',
'angular-sanitize': '../../bower_components/angular-sanitize/angular-sanitize',
'angular-touch': '../../bower_components/angular-touch/angular-touch',
'bootstrap': '../../bower_components/bootstrap/dist/js/bootstrap',
'ol': '../../bower_components/openlayers3/build/ol',
'angular-openlayers-directive': '../../bower_components/angular-openlayers-directive/dist/angular-openlayers-directive.min'
},
shim: {
angular: {
exports: 'angular'
},
'angular-route': [
'angular'
],
'angular-cookies': [
'angular'
],
'angular-sanitize': [
'angular'
],
'angular-resource': [
'angular'
],
'angular-animate': [
'angular'
],
'angular-touch': [
'angular'
],
'angular-mocks': {
deps: [
'angular'
],
exports: 'angular.mock'
},
'angularAMD': ['angular'],
'angular-openlayers-directive': {
deps: [
'ol',
'angular',
'angular-sanitize'
]
},
// 'ol': {
// expors: 'ol'
// }
},
priority: [
'angular'
],
packages: [

]
});

**Comment by juristr** [comment]
Hi, 

yes, noticed that as well. Do you have a fix for this?

I currently expose `ol` publicly on the window object which is kinda hacky, but works. If you gave a better fix, I'd be happy to accept a PR :smiley:

**Comment by realrnjs** [comment]
Hi. :smiley:
Yes. I'll change the way I know.

**Comment by juristr** [comment]
@realrnjs I'm closing as this should be resolved with the merge of your PR, right? Reopen if necessary. Thx again!
