### ISSUE TITLE
openlayers.map.singleclick not working

### ISSUE THREAD

**Issue by th0m** [tombatossals/angular-openlayers-directive#172]
Hi tombatossals,

Example 084 is broken as well as http://tombatossals.github.io/angular-openlayers-directive/#/events/event-defaults.
It seems that neither openlayers.map.pointermove nor openlayers.map.singleclick events are triggered, therefore the code in $scope.on is never executed.

Thanks for your help,
Thomas.

**Comment by jessemarple** [comment]
+1 for this

**Comment by BenSower** [comment]
This only seems to be a problem with the embedded version. Even though the embedded version did not work, the source-equal standalone version mentioned at the bottom of the page worked for me:
http://tombatossals.github.io/angular-openlayers-directive/examples/080-events-propagation-example.html

**Comment by jessemarple** [comment]
@th0m - have you made certain to register the event first?

e.g.

<pre>
        . . . 
        angular.extend($scope, {
            //override defaults controls
            defaults: {
              controls: {
                zoom: false,
                rotate: false,
                attribution: false
              },
              events: {
                  map: [ 'change', 'change:layerGroup', 'change:size', 'change:target', 'change:view', 'click', 'dblclick', 'moveend', 'pointerdrag', 'pointermove', 'postcompose', 'postrender', 'precompose', 'propertychange', 'singleclick' ],
                  markers: [ 'change', 'change:layerGroup', 'change:size', 'change:target', 'change:view', 'click', 'dblclick', 'moveend', 'pointerdrag', 'pointermove', 'postcompose', 'postrender', 'precompose', 'propertychange', 'singleclick' ],
                  // pointsOfInterest: [ 'change', 'change:layerGroup', 'change:size', 'change:target', 'change:view', 'click', 'dblclick', 'moveend', 'pointerdrag', 'pointermove', 'postcompose', 'postrender', 'precompose', 'propertychange', 'singleclick' ]
              }
            },
      . . .
</pre>

**Comment by juristr** [comment]
Hey guys. I'm currently in vacation, writing this comment from Las Vegas :wink: . I'll only be back in a couple of weeks. In the mean time, can you create some Plunkr to reproduce the issue, or even better, a PR with a test that verifies the problem is solved?? That'd be super awesome!

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).
