### ISSUE TITLE
Using OpenLayers Directive with Browserify

### ISSUE THREAD

**Issue by jessemarple** [tombatossals/angular-openlayers-directive#174]
I'm unable to load the directive with Browserify. 
<pre>
require('openlayers');
require('angular');
require('angular-sanitize');
require('angular-openlayers-directive');

var app = angular.module("demoapp", ["openlayers-directive"]);
</pre>
The result is always:
<pre>Cannot read property 'style' of undefined</pre>

As far as I can tell, the module is loading. It simply doesn't seem to be seeing OL, even when I expressly set <pre>var ol = require('openlayers')</pre>

I've tried shimming but that doesn't seem to work either. My shim looks like this:

<pre>
    "angular-openlayers-directive": {
      "depends": ["openlayers","angular","angular-sanitize"],
      "exports": "angular.module('openlayers-directive').name"
    }
</pre>

Any suggestions for using with Browserify?

**Comment by claustres** [comment]
Which version of OL3 are you using ? Master should be used with 3.8, maybe this is relate : https://github.com/tombatossals/angular-openlayers-directive/issues/185.

**Comment by jessemarple** [comment]
I'm deep in the weeds with implemetnaiton but I will be adding this ( "fix" in #182 )in shortly. If it works, I'll close.

**Comment by tangram** [comment]
I can't get this to work either. Did you get anywhere with browserify, @jessemarple?

**Comment by karsunke** [comment]
+1

**Comment by claycephas** [comment]
+1 same `cannot read style of undefined` error with webpack

**Comment by jewelcai** [comment]
May be you need to change the sequence of js files when lodading, ol should come before the directive
