### ISSUE TITLE
Does anyone know how to draw a circle?

### ISSUE THREAD

**Issue by zardaloop** [tombatossals/angular-openlayers-directive#178]
I am really new to the Openlayer3 and I would appreciate if someone could help me. I am trying to do something like this  
```javascript
var circle = new ol.Feature({
                geometry: new ol.geom.Circle(new ol.Coordinate([-132567.2, 6750918]), 200)
            });
```
by following the documentation from here : http://openlayers.org/en/v3.8.1/apidoc/ol.geom.Circle.html

Obviously what I have here is not correct but I can't find any proper example for that. 

Many thanks in advance.

**Comment by juristr** [comment]
That's something you have to find on the Open Layers docs or example pages. When you have that, you can get access to the raw open layers map through this library as follows:

```javascript
// inject olData with Angular
olData.getMap().then(function(map) {

});
```
..and then use the native openlayers3 API to add appropriate features to draw circles or whatever you need :smile: 

Hope that helped you out. I'm closing this issue for now.
