### ISSUE TITLE
Markers size

### ISSUE THREAD

**Issue by saledo** [tombatossals/angular-openlayers-directive#182]
Is it possible to change marker's custom icon image size?
If i set inside style size like this
                                    style: {
				                image: {
				                    icon: {
				                        anchor: [0.5, 0.5],
				                        anchorXUnits: 'fraction',
				                        anchorYUnits: 'fraction',
				                        opacity: 1,
                                                        size: [12, 12]
				                        src: 'images/map-marker.png'
				                    }
				                }
			            	}
it only changes markers size on 12px x 12px but inside image stays in original size. 
Can i change size of image that I'm using for marker using directive?

**Comment by saledo** [comment]
After some research i found answer. There is parameter scale in OpenLayers3 ol.style.Icon and it can be used here in this directive.

style: {
    image: {
        icon: {
            anchor: [0.5, 0.5],
            anchorXUnits: 'fraction',
            anchorYUnits: 'fraction',
            opacity: 1,
            scale: 0.5,
            src: 'images/map-marker.png'
            }
        }
    }
I used this question for help
http://stackoverflow.com/questions/28888025/how-do-i-decrease-the-size-of-icon-in-openlayers-3-i-am-using-bing-maps

**Comment by juristr** [comment]
:+1: thx for your answers!
