### ISSUE TITLE
Click event on makers generated from geojson

### ISSUE THREAD

**Issue by hardboy111** [tombatossals/angular-openlayers-directive#187]
Hi All,

I'm trying to attach click events to each marker displayed on a map. Is there a similar event callback available for dynamically added markers like in the following example that has an openlayers.layers.geojson.click event I can listen on.

http://tombatossals.github.io/angular-openlayers-directive/#/events/event-vector-layer

Any help much appreciated,

Mike

**Comment by jessemarple** [comment]
Hey Mike - I tend to include my onClick function as part on my 'marker creation' factory.
<pre>
Factory.makeSiteMarker = function(layerId, marker, location, layerStyle, onClickFunction){ . . . }
</pre>

In this way, I can dynamically add the onClick function to the markers I create.

I tend to stay away from calling $scope.apply(...).

**Comment by hardboy111** [comment]
Hi Jesse,

Thanks for the suggestion - I've now included a similar approach in my app that works. The documentation is a little light re: markers compared to layers so was assuming there might had been a similar $emit<>$on model.

..I'll close this now.
