### ISSUE TITLE
TileWMS Layer not rendering on map ? 

### ISSUE THREAD

**Issue by hardboy111** [tombatossals/angular-openlayers-directive#188]
Hi All,

Im trying to load a WMS service into my map using the following configuration:
layer: {
                        source: {
                            type: 'TileWMS',
                            crossOrigin:null,
                            url: 'http://wms.openweathermap.org/service',
                            params: { LAYERS: 'precipitation_cls'}
                        }
                    }

But it isnt rendering on the map. I originally had a CORS issue which I resolved by adding in crossOrigin:null as part of the source but now I get no error but also no layer.

The http request being generated looks like this:

http://wms.openweathermap.org/service?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=precipitation_cls&WIDTH=256&HEIGHT=256&CRS=EPSG%3A900913&STYLES=&BBOX=-2504688.542848654%2C7514065.628545966%2C-1878516.40713649%2C8140237.7642581295

I can't see what I'm doing wrong.

Any help much appreciated,

Mike

**Comment by hardboy111** [comment]
just as an update when I put the GET into a web browser I get a 404 (Could not get any sources: HTTP Error "http://127.0.0.1:83/tile/tilecache.cgi/1.0.0/precipitation_cls/6/36/19.png": 404).

I've also just discovered this site (http://wms.openweathermap.org/demo/#) which would indicate the title server is down and not a problem with the ol3 directive ?

Thx,

Mike

**Comment by hardboy111** [comment]
although this example would suggest I need to create a XYZ source type http://openweathermap.org/help/tiles.html?opacity=1&l=precipitation

I'll look into whether this is possible with the ol3 directive.

**Comment by Pedrazl** [comment]
Hi @hardboy111,
I load WMS layers with the directive in that way:
```javascript
var layers= [
{
                name: 'YourLayerName',
                active: true,
                source:
                {
                    type: 'ImageWMS',
                    url: yourURL,
                    params: {
                        LAYERS: 'NameOfLayerInsideWMS',                                   
                        opacity: '66'                                           
                    }
                }            
}]
```
And on your html:
<ol-layer ol-layer-properties="layer" ng-repeat="layer in layers|filter:{active:true}"></ol-layer>

That should be fine if the wms service you are pointing is working. 
Hope it helps,

**Comment by hardboy111** [comment]
Hi @Pedrazl,

Thanks for the response - I finally got the title service rendering but I had to edit the library to handle another source type I named 'TileXYZ' e.g.:

```
                case 'TileXYZ':
                if (!source.type || !source.url) {
                    $log.error('[AngularJS - Openlayers] - TileXYZ layer requires source type and XYZ formatted url');
                    return;
                }
                oSource = new ol.source.XYZ({
                    url: source.url,
                    crossOrigin: (typeof source.crossOrigin === 'undefined') ? 'anonymous' : source.crossOrigin
                });
                break;
```

Thanks,
Mike
