### ISSUE TITLE
scaleline and zoomslider control not showing

### ISSUE THREAD

**Issue by poca2k** [tombatossals/angular-openlayers-directive#189]
Im trying to add the scaleline and zoomslider control but they are not showing, all the other controls work fine but this ones dont show, what can i do?
this are my controls

```
controls: {
            zoom: false,
            rotate: false,
            attribution: false,
            fullscreen: true,
            scaleline:true,
            zoomslider:true,
            
          }
```

**Comment by jessemarple** [comment]
@poca2k - the best answer to your question is here:
https://github.com/tombatossals/angular-openlayers-directive/blob/master/examples/104-controls-options-example.html

It's very very important to note that when setting your controls, there's the defaults, the actual settings, and the markup. Look at the source of that example and you'll see how to do this.

**Comment by poca2k** [comment]
Ive tryed that, but scaleline and zoomslider still wont work.
ive added 
{ name: 'scaleline', active: true },
{ name: 'zoomslider', active: true}

and still wont work
