### ISSUE TITLE
Goals for interactions

### ISSUE THREAD

**Issue by danieldooley** [tombatossals/angular-openlayers-directive#197]
Hi

Loving this directive effort so far. Is there any future goals for having directives allowing better access to the interactions present in OL3? Draw etc.

Thanks

**Comment by juristr** [comment]
Hi, what exactly are you thinking about. Could you describe in more detail?

**Comment by caiobelfort** [comment]
I guess he wants something like  managment the of controls. Have same request, but i guess exist a form to do that in other manner
