### ISSUE TITLE
Canvas Setting to "display:none" on re size of the Collapsed Tab.

### ISSUE THREAD

**Issue by dharanid** [tombatossals/angular-openlayers-directive#199]
Hi ,
 I created the map Widget using Open layer angular directive. I'm Getting a Strange Problem when i'm placing the map widget inside an Accordion kind of container.

Steps to Reproduce My Issue
1. Collapse the Map Section
2. Re size the Browser Screen
3. Expand the Map Section( Now the Map was not rendering, instead display:none was attached to the Canvas Element)

Please let me know if you have any ideas on this issue

Note: when i manually set the display to block.( Map was displayed, but default controls are not working)

Thanks 
Dharani

**Comment by juristr** [comment]
@dharanid Hmm...really strange issue. Unfortunately I'm currently quite busy to reconstruct this. Could you provide a [Plunker](http://plnkr.co/) (or JSBin, JSFiddle, whatever) that reproduces this issue??

That would help a lot, thx :smiley:

**Comment by dharanid** [comment]
Thanks @juristr for the Response

I recreated the issue in the following link

http://plnkr.co/edit/7FPyjfQP76FqJN4gB2Qt?p=preview

**Comment by dulcedilip** [comment]
Appreciate for help myself having same issue.

**Comment by juristr** [comment]
Should be resolved by now. See referenced issue on the ol3 repository.
