### ISSUE TITLE
Multiple Layer Z-index Problem

### ISSUE THREAD

**Issue by dharanid** [tombatossals/angular-openlayers-directive#200]
Hi

I created multiple layers using "ol-layer" directive.
I'm not sure how to show one layer set to be above the other layer always.
Like how markers are above layers

Any help would be appreciated.

Thanks
Dharani

**Comment by juristr** [comment]
The layer has to be the top-most, that is if you have something like this:

```html
<openlayers ol-center="map.center" ol-defaults="map.mapConfig" custom-layers="true">
	<ol-layer name="{{ layer.name }}" ol-layer-properties="layer" ng-repeat="layer in vm.registeredLayers">
	</ol-layer>
</openlayers>
```

and in your directive's code

```
function DirectiveController() {
  var vm = this;

  vm.registeredLayers = [
     {
       name: 'Layer 1',
       visible: true,
       source: { ... }
     },
     {
       name: 'Layer 2',
       visible: true,
       source: { ... }
     },
     {
       name: 'Layer 3',
       visible: true,
       source: { ... }
     }
  ];
}
```

..then Layer 2 would be displayed on top of Layer 1 and Layer 3 on top of Layer 2. Hope that's clear enough.

**Comment by dharanid** [comment]
Thanks @juristr for the response
But in My case I'm using like below

```
<openlayers ol-center="map.center" ol-defaults="map.mapConfig" custom-layers="true">
    <ol-layer name="{{ layer.name }}" ol-layer-properties="layer" ng-repeat="layer in    vm.registeredLayers">
        </ol-layer>
    <ol-layer name="{{ layer.name }}" ol-layer-properties="layer" ng-repeat="layer in vm.registeredLayers2">
       </ol-layer>
</openlayers>
```

**Comment by dharanid** [comment]
@juristr 

I still couldn't fix the issue... please help me.
if you have any ideas or suggestions.

**Comment by juristr** [comment]
@dharanid Can u plz provide a Plunkr that reproduces the issue? You can start forking this one:
http://plnkr.co/edit/Ky1UnQ3LSFu78CaiJxPc?p=preview

**Comment by dharanid** [comment]
Hi @juristr 

I created a plunker with my exact problem
http://plnkr.co/edit/defFbc?p=preview

I have 4 tile types in my first layer group array.
Apart from that i have another layer group which contain site polygon etc.

while switching tile layer... my site polygon layer is going behind the Tile layers which i needs to be available at the top all the time irrespective of my tile layer.

Please feel free to ping me if you have any questions.

Thanks in advance.

**Comment by lautarobock** [comment]
I have the same problem

**Comment by lautarobock** [comment]
@dharanid you can use index property to load layers in the order do you want

**Comment by dharanid** [comment]
Sorry for the late response.....that's how I fixed the issue.....

**Comment by lautarobock** [comment]
@dharanid Great!
