### ISSUE TITLE
Draw feature Example   

### ISSUE THREAD

**Issue by fpanchoro** [tombatossals/angular-openlayers-directive#209]
Please  exist  some example to Draw feature.

Open Layer have this example:

http://openlayers.org/en/master/examples/draw-features.html

**Comment by stephenHartzell** [comment]
Yes, please do!

**Comment by juristr** [comment]
For these scenarios we currently use the api to get hold of the underlying ol3 map object and use the ol3 api directly.

**Comment by juristr** [comment]
Example:

```javascript
olData.getMap().then(function (map) {
  // map is the native ol3 object. use the ol3 api to draw features on top of existing layers
});
