### ISSUE TITLE
Add marker to a existing marker array move old markers in the array

### ISSUE THREAD

**Issue by humaknight** [tombatossals/angular-openlayers-directive#210]
When you add new markers to  a existing marker array. The old markers move from her position to the top of the screen.

**Comment by humaknight** [comment]
I am triying solve the problem.

I detect when you added new elements in ng-repeat. ol-marker Link funtion not called for the old elements.

**Comment by humaknight** [comment]
Finally I clone the old array, put new marker in new array later I destroy the marker array and copy the marker array:

var markerstemp = angular.copy($scope.markers);
			markerstemp.push(marker);
			$scope.markers = [];
			$scope.markers = markerstemp;

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).
