### ISSUE TITLE
enable scroll to zoom control

### ISSUE THREAD

**Issue by jgastonraoul** [tombatossals/angular-openlayers-directive#217]
Hi !

I haven't been able to activate scroll wheel zoom control.
Any idea on how to do that ? 

Regards,

Jeremie

**Comment by juristr** [comment]
HI @jgastonraoul ,

you can pass it in the configuration, like

```javascript
function SomeController() {
  var vm = this;
  ...
   vm.mapConfig = {
      ...
      interactions: {
         mouseWheelZoom: true
      }
   };
   ...
}
```

And bind it to the openlayers directive like

```html
<openlayers ol-defaults="vm.mapConfig">
   ...
</openlayers>
```

Hope that helps. I'm closing the issue. Feel free to re-open it in case.

**Comment by jgastonraoul** [comment]
That's what I was doing, but there was a mistake in my directive : I was using "defaults" instead of "ol-defaults'.

Thanks for your help.

**Comment by juristr** [comment]
:+1:
