### ISSUE TITLE
How to use OL3, center:bounds 

### ISSUE THREAD

**Issue by SeratFatima** [tombatossals/angular-openlayers-directive#223]
I am currently trying to update map bounds by passing bounds available on map center using the following code:

In Controller:
            this.center = {
                bounds: this.mapExtents
            };

here I am updating the map extent using the following logic:
            this.mapExtents[0] = data[0].lat;
            this.mapExtents[2] = data[0].lat;
            this.mapExtents[1] = data[0].lon;
            this.mapExtents[3] = data[0].lon;

Iterating through marker data and returning the this.mapExtents by following logic:

       if (data[i].lat < this.mapExtents[0]) {
                    this.mapExtents[0] = data[i].lat;
                }
                if (data[i].lon < this.mapExtents[1]) {
                    this.mapExtents[1] = data[i].lon;
                }
                if (data[i].lat > this.mapExtents[2]) {
                    this.mapExtents[2] = data[i].lat;
                }
                if (data[i].lon > this.mapExtents[3]) {
                    this.mapExtents[3] = data[i].lon;
                }

This does not seem to work throws the following error:

Failed to execute 'putImageData' on 'CanvasRenderingContext2D': The provided float value is non-finite.

Even while using the hardcoded valid bounds as following I get the same error:
            this.center = {
                bounds:   [   
                                -87.865114442365922,
                               43.665065564837931,
                               -87.595394059497067,
                                43.823852564430069
                              ]
                       };

Please let me know how to make use of these bounds available on center.

**Comment by Pedrazl** [comment]
Hi @SeratFatima , I think you may have the order of coordinates wrong. It should be MinLongitude, MinLatitute, MaxLongitude, MaxLatitude.

**Comment by juristr** [comment]
@SeratFatima closing this issue. Please re-open it if it still persists.
