### ISSUE TITLE
Exposing WKT format for Vector Features

### ISSUE THREAD

**Issue by SeratFatima** [tombatossals/angular-openlayers-directive#225]
Hi, I am requesting for the support for WKT format on the directive as I read in the below stackexchange link that WKT format is supported on OL3 then why not include this format for plotting geometry in the Directives :
http://gis.stackexchange.com/questions/92888/does-openlayers3-support-wkt-format

Example:
http://openlayers.org/en/v3.0.0/examples/wkt.html

**Comment by lautarobock** [comment]
why closed? is this supported in angular version?

**Comment by juristr** [comment]
Hi @lautarobock , the author closed the issue by himself. If you find this useful, feel free to send us a PR :smiley:

**Comment by lautarobock** [comment]
@juristr is true, it was the proper author.
