### ISSUE TITLE
Fix broken JSONP layers - ServerVector no longer supported by OL3

### ISSUE THREAD

**Issue by craigsnyders** [tombatossals/angular-openlayers-directive#234]
https://github.com/openlayers/ol3/blob/master/changelog/v3.5.0.md

Currently depends on openlayers ~3.8 however since v3.5.0 ol.source.ServerVector is removed in favour of ol.source.Vector.  There are also a couple of other minor code changes.  

I'm planning to submit a PR in about 1 week from now for this

**Comment by juristr** [comment]
:+1: thx

**Comment by juristr** [comment]
@craigsnyders We've just released a version that supports the latest 3.16 release of ol3.
