### ISSUE TITLE
Dynamic GeoJSON unable to project to mercator.

### ISSUE THREAD

**Issue by Pedrazl** [tombatossals/angular-openlayers-directive#240]
Hi,
I realised that with the new version of the library, geoJSON objects doesn´t render properly on the map. In my app, I get some geoJSON features at WGS84 (EPSG:4326), but when I try to render them on the map, they are in wrong positions. After a little bit investigation I found the problem: 
```javascript
oSource = new ol.source.Vector();

                    var projectionToUse = projection;
                    if (isDefined(source.geojson.projection)) {
                        projectionToUse = source.geojson.projection;
                    }

                    var features = geojsonFormat.readFeatures(
                        source.geojson.object, {
                            featureProjection: projectionToUse
                            dataProjection: projectionToUse 
                        });

                    oSource.addFeatures(features);
                }
```
As you can see, "projectionToUse" is the same for both so it`s impossible to make the transformation from data source projection to Mercator. 
My solution right now is to comment the dataProjection line, but there should be a better solution, maybe injecting the original projection or something like that.

**Comment by juristr** [comment]
Could you submit a PR for this? That'd be awesome. Unfortunately I currently have no time to investigate further, atm.

**Comment by Pedrazl** [comment]
Sure, I will find some time to make the PR.

**Comment by juristr** [comment]
@Pedrazl Awesome!

**Comment by Pedrazl** [comment]
@juristr I already fixed it. Here is the PR, https://github.com/tombatossals/angular-openlayers-directive/pull/242
Hope everything is fine now!
