### ISSUE TITLE
Tests fail with angular 1.5

### ISSUE THREAD

**Issue by juristr** [tombatossals/angular-openlayers-directive#241]
Seems like tests fail when upgrading to angular 1.5.

PR welcome :wink:

**Comment by koihatano** [comment]
I try to use angular 1.5.6, Unit Tests passed all, 'cause upgrade opanlayers, I guess.

**Comment by juristr** [comment]
Ya, in fact, when I was doing some house keeping on these issues, I actually closed it ~3 days ago. Problems which get solved alone over time are always welcome :wink:
