### ISSUE TITLE
Toggle categories of markers

### ISSUE THREAD

**Issue by notph** [tombatossals/angular-openlayers-directive#244]
Hi,

I'm presently working on a toogle capability for "categories" of markers but somethink's going wrong...

http://jsfiddle.net/uhLf95wr/

Simple nothing happens when I toogle them.

Any idea?

**Comment by anushamc** [comment]
Hi,
In your fiddle you are updating <code>markSEA</code> and <code>markGB</code> but in your html and in the scope you are passing <code>markers</code>. If you change it to refer to the right objects in scope and html, it works.

http://jsfiddle.net/anushamc/sqtt4y39/

Hope this helps.

**Comment by juristr** [comment]
@anushamc Thanks a lot for helping people here on this repo. Really valuable :+1:
