### ISSUE TITLE
Overviewmap issue

### ISSUE THREAD

**Issue by kamou31** [tombatossals/angular-openlayers-directive#250]
Hello,

The overviewmap control seems to not be working with this directive. 
I've added it in the controls of my map like this : 
```
angular.extend($scope, {
        center: {
                lat: 8.7968,
                lon: 104.9166,
                zoom: 10
        },
        layers: [
	        {		
				name: "layer1", 
				"source": {
				    "name": "Bing Maps",
				    "type": "BingMaps",
				    "key": "myKey",
				    "imagerySet": "Road"
				},
				opacity: 0.75,
				visible: true,
				active: true,

			},
		],
            controls: [
                { name: 'overviewmap', active: true, collapsed:false }
            ]
    });
```
But it's not working. I got an error "Error: i[c.name] is not a constructor"
Is it possible to get the map object initialized by the directive ?

Thank you

**Comment by anushamc** [comment]
Hello,
How are you accessing the controls in the directive in the html file? Are you using the <ol-control></ol-control> directive? I've created a fiddle at http://jsfiddle.net/anushamc/yxtn8syx/ and it seems to be working that way.

**Comment by juristr** [comment]
@kamou31 I'll close this. If it's still not solved, feel free to re-open the issue. thx!
