### ISSUE TITLE
Turn off default OSM Layer

### ISSUE THREAD

**Issue by crlsmtzprds** [tombatossals/angular-openlayers-directive#254]
I'm using ol3 with my WMS, I need turn off the layer of OSM which is loading by default to use only my custom wms layer. How can I do that?

https://github.com/tombatossals/angular-openlayers-directive/blob/master/examples/040-layers-change-tiles-example.html

In this example the layer "osm" have set an active property and the layer visibility is switching by the button, but in my case and need just load my wms tile layer and I want to the OSM layer that OL3 isn't load by default, the example property is not working for me because if I set the OSM (which is loading apart of the default) if I set off manually the layer OSM the OSM default don't turn off.

I used this example
https://github.com/tombatossals/angular-openlayers-directive/blob/master/examples/053-layers-image-wms-example.html

```javascript
<openlayers ol-center="campos.setDefault.marker" height="480px" width="100%">
		    		<ol-layer ol-layer-properties="wms"></ol-layer>
		    		<ol-layer ol-layer-properties="osm"></ol-layer>
		    		<ol-marker lat="campos.setDefault.marker.lat" lon="campos.setDefault.marker.lon"></ol-marker>
		    	</openlayers>
```

```javascript  
angular.extend($scope, {
        center: {
            lat: 19.839,
            lon: -90.52,
            zoom: 4
        },
        wms: {
                active: true,
                    source: {
                        type: 'ImageWMS',
                        serverType: 'mapserver',
                        url: 'http://127.0.0.1/cgi-bin/mapserv?map=/var/www/mymap.map',
                        crossOrigin: null,
                        params: { 
                            LAYERS: '-----',
                            TILED: true,
                            FORMAT : 'image/jpeg',
                            attribution: '----'
                             },
                        serverType: ('mapserver')
                    }
                },
        osm :  {
                        name: 'OpenStreetMap',
                        active: false,
                        source: {
                            type: 'OSM'
                        }
        }
    });
```

**Comment by anushamc** [comment]
Hi, have you tried setting the attribute custom-layers="true" in the <openlayers> directive?

**Comment by crlsmtzprds** [comment]
Thank you, with this attribute my problem was solved
