### ISSUE TITLE
Provide a geoJSON source doesn't seem to work with the latest version

### ISSUE THREAD

**Issue by aubm** [tombatossals/angular-openlayers-directive#259]
I have been playing with a few examples, starting with the one that came from #26, it seems that providing a hard coded geoJSON source doesn't work with the latest version of the directive.

I created a plunker to highlight the issue:
https://plnkr.co/edit/5aIfjypfsFOD9q1RyxGC?p=preview

Maybe I'm missing something?

@davinkevin

**Comment by davinkevin** [comment]
The problem appears after the merged of this PR : https://github.com/tombatossals/angular-openlayers-directive/pull/233/files

You can see this problem in the 55th example which isn't working

**Comment by yong2khoo88** [comment]
I am facing the same problem. And has posted in the [stackoverflow post](http://stackoverflow.com/questions/36907390/openlayers-angularjs-always-shows-geojson-point-at-0-0).
Any fix available?

**Comment by juristr** [comment]
I'm closing this issue as apparently there's an [accepted answer on StackOverflow](http://stackoverflow.com/questions/36907390/openlayers-angularjs-always-shows-geojson-point-at-0-0)
