### ISSUE TITLE
Allow setting loadTilesWhileAnimating and loadTilesWhileInteracting map options via ol-defaults

### ISSUE THREAD

**Issue by sergkr** [tombatossals/angular-openlayers-directive#261]
OpenLayers 3 supports the following properties when initializing the map:

* `loadTilesWhileAnimating`: When set to true, tiles will be loaded during animations. This may improve the user experience, but can also make animations stutter on devices with slow memory. Default is false.
* `loadTilesWhileInteracting`: When set to true, tiles will be loaded while interacting with the map. This may improve the user experience, but can also make map panning and zooming choppy on devices with slow memory. Default is false.

I wanted to use these options in my project, but I noticed it is not possible to set them via this directive. It looks like these options simply need to be copied over in [olMapDefaults.js](https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/services/olMapDefaults.js).

Any objections to adding support for these options? I can submit a PR if needed.

**Comment by juristr** [comment]
@sergkr Sure, would be cool if you could submit a PR for this. I can then review and merge it in :+1:

**Comment by juristr** [comment]
@sergkr We could pass them in through the [defaults property of the map](https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/directives/openlayers.js#L9) and then [assign it here accordingly](https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/directives/openlayers.js#L70). What do you think?

**Comment by sergkr** [comment]
Opened #277.

@juristr I made the changes you suggested, and also changed `olMapDefaults.js`. Otherwise, in `openlayers.js` we would need to copy those properties from `scope.defaults.loadTilesWhileAnimating` and `scope.defaults.loadTilesWhileInteracting`, instead of `defaults.loadTilesWhileAnimating` and `defaults.loadTilesWhileInteracting`, which seemed contrary to how some of the other properties (`renderer`) were being copied.
