### ISSUE TITLE
Cluster break functionality not working with OL3 3.14 and Angular 1.5.5

### ISSUE THREAD

**Issue by SeratFatima** [tombatossals/angular-openlayers-directive#272]
Hi,

We are trying to create the clusters based on different points nearby and break the same on zoom.
For doing this we are using angular-openlayers directive with following dependency for OL3 and Angular
1. OL3 ~3.14
2.Angular ^1.4.8

Reason for OL3 ~3.14 -  If we use the version below this we face an issue of **Maps getting rotated on zoom change in IE11**
Reason for Angular^1.4.8 is to get the most latest version for angular (1.5.5)

Please let me know if someone has faced this issue or the possible solution for one of the two problems above:
**Problem 1**. IE11- Maps should not rotate on zoom change along with cluster functionality working fine
**Problem 2**. Get the support of latest and stable Angular version

Thank you.

Regards,
Serat Fatima

**Comment by juristr** [comment]
Hi @SeratFatima. Thx for reporting. Could you please dive deeper into these issues and identify whether it lies within the angular-openlayers-directive or the underlying version of ol3?

Also related to the support for the latest Angular version. What kind of issues do you encounter with it?

**Comment by SeratFatima** [comment]
I find this issue appearing with lower versions of openlayers when used with Angular openlayers i.e. Version **below 3.14 causes map tiles changing orientation on zoom**
On updating **Angular to 1.5.5 cluster break functionality hinders**.

I am looking forward for updating my Angular to 1.5.5 without getting cluster break functionality affected.
Also openlayers to 3.14 to prevent may orientations issue.

Thank you.

Regards,
Serat Fatima

**Comment by juristr** [comment]
This should be fixed by #275. In case please re-open the issue.
