### ISSUE TITLE
Style not working on (GeoJSON) Point?

### ISSUE THREAD

**Issue by kdekooter** [tombatossals/angular-openlayers-directive#29]
This is probably an utter noob question but I am not able to style my GeoJSON layer properly. This is my source:

```
{
    type: 'FeatureCollection',
    features: [
      {
        type: 'feature',
        geometry: {
          type: 'Point',
          coordinates: [4.351676, 51.911728]
        }
      }
```

Which are displayed properly in de OL default style. The moment I try to style it like this:

```
        style: {
          fill: {
            color: '#FF0000'
          },
          stroke: {
            color: '#FFFFFF',
            width: 3
          }
        },
```

the points are no longer visible.

**Comment by jsheedy** [comment]
I was having trouble styling a collection of points too, but it worked fine with a pointToLayer function on the geojson.   Here's a plunker: http://plnkr.co/edit/5mtrNCVXWmmHnkeWTG5u?p=preview
