### ISSUE TITLE
maker directive has memory leaks

### ISSUE THREAD

**Issue by NiclasLindgren** [tombatossals/angular-openlayers-directive#290]
Unless I am doing something wrong I believe the marker directive has memory leaks with its event handlers. If I run a loop removing and adding the same set of markers the browser will slowly increase memory and finally be unresponsive

Most of the leaks goes away if we don't register the handlers

I believe the issue is with

                //map.on('pointerdown', handleDrag);
                //map.on('pointerup', handleDrag);
                //map.on('pointerdrag', handleDrag);

As well as the touch/click handlers (note the return before the handler setup)

                    if (label && properties.label && properties.label.show === false) {
                        map.removeOverlay(label);
                        label = undefined;
                    }
                    return;
                    // Then setup new ones according to properties
                    if (properties.label && properties.label.show === false &&

And comment out the touchend
                        // Preventing from 'touchend' to be considered a tap, if fired immediately after 'touchmove'
                        // map.getViewport().querySelector('canvas.ol-unselectable').addEventListener(
                            'touchmove', activateCooldown);

After that, it leaks substantially less.

I tried adding deregistration in destroy, but failed to make it work, newbie at angular so not sure what I am doing really..

                scope.$on('$destroy', function () {
                    if (marker) {
                        markerLayer.getSource().removeFeature(marker);
                    }
                    if (isDefined(label)) {
                        map.removeOverlay(label);
                    }
                    markerLayerManager.deregisterScope(scope, map);
                    map.un('pointerdown', scope.handleDrag);
                    map.un('pointerup', scope.handleDrag);
                    map.un('pointerdrag', scope.handleDrag);
                    map.getViewport().removeEventListener('mousemove', scope.properties.handleInteraction);
                    map.getViewport().removeEventListener('click', scope.properties.handleTapInteraction);
                    map.getViewport().querySelector('canvas.ol-unselectable').removeEventListener(
                        'touchend', scope.properties.handleTapInteraction);
                    map.getViewport().removeEventListener('mousemove', scope.properties.showAtLeastOneOverlay);
                    map.getViewport().removeEventListener('click', scope.properties.removeAllOverlays);
                    map.getViewport().querySelector('canvas.ol-unselectable').addEventListener(
                            'touchmove', scope.properties.touchmove);
                });

I ran the same scenario directly with openlayers3 without the directive and it does not seem to leak at all. 

I just have 5 markers(with a label), removed and added every 1s, it leaks 100mb in a few minutes, after removing the handlers it "leaks" 1M in the same time. Which I am not sure it is a leak even, because I seem to be able to force GC collect that part

If I make it work I will supply the code

**Comment by juristr** [comment]
Hi, if you manage to submit a PR for this, that would be super awesome :+1:

**Comment by NiclasLindgren** [comment]
I am a github newbie, never done a PR before (or angular), but I tried

https://github.com/tombatossals/angular-openlayers-directive/pull/293

**Comment by NiclasLindgren** [comment]
I have run a 4 hour test, one with the fix, and another with a return statement on the "link" function, thus not creating any markers.

Both instances "leak" the same amount. Which likely means the bug is fixed and there is a retention issue somewhere else. But efter 4 hours only 3MB has been used up, prior to the fixed it was in the hundreds of megs.

**Comment by juristr** [comment]
> I am a github newbie, never done a PR before (or angular), but I tried

That is awesome. I'm going to take a look at it later and let you know. :smiley:
