### ISSUE TITLE
npm dependency broken

### ISSUE THREAD

**Issue by njirem** [tombatossals/angular-openlayers-directive#311]
Since about 15 hours, the npm install of angular-openlayers-directive fails.
This seems to be because it requires openlayers 3.8.x, which requires jsdoc 3.3.0-alpha9 (as non-dev dependency, but that's another story), which requires the master branch of https://github.com/hegemonic/taffydb.

The problem with this is that the package name of this branch has changed. From jsdoc 3.3.2/openlayers 3.9.0 forward, this has been fixed by requiring a specific commit.

Is is possible to upgrade the openlayers dependency to a newer version, at least 3.9.0?

**Comment by juristr** [comment]
oh ok. Would you be willing to do a PR for this?

**Comment by njirem** [comment]
Of course :-)

**Comment by juristr** [comment]
@njirem Awesome!! Looking forward to. Make sure you check out our [Contribution guidelines](https://github.com/tombatossals/angular-openlayers-directive/blob/master/CONTRIBUTING.md) :wink:
