### ISSUE TITLE
Checking for undefined in $destroy handler

### ISSUE THREAD

**Issue by ekerkenaar** [tombatossals/angular-openlayers-directive#314]
When using version 1.15.2, our unit tests report the follow error:
undefined is not an object (evaluating scope.properties.handleInteraction)

This seems to be caused by an undefensive teardown when using a marker without any properties attached.

(Reporting this issue on behalf of @njirem who will send you a PR soon).

**Comment by ekerkenaar** [comment]
Cool @njirem That was quick ;)

**Comment by njirem** [comment]
You're welcome. :-) Build still fails because of issue #311 though.

**Comment by juristr** [comment]
@ekerkenaar @njirem Great stuff guys! I merged in everything. The build chain should pick up soon and publish everything out on npm and bower. Thx a lot! :+1:
