### ISSUE TITLE
Examples seem to be broken

### ISSUE THREAD

**Issue by zzats** [tombatossals/angular-openlayers-directive#32]
I'm not sure if I'm the problem lies between (my) chair and keyboard, but to me it seems like the ol-marker -directive is broken in the 0.0.2 release and the online examples.

Marker(s) not visible:
http://tombatossals.github.io/angular-openlayers-directive/examples/060-marker-example.html
http://tombatossals.github.io/angular-openlayers-directive/examples/061-markers-add-remove-example.html

Marker not visible, label visible:
http://tombatossals.github.io/angular-openlayers-directive/examples/062-markers-label-example.html

Markers not visible, showOnMouseOver has no effect:
http://tombatossals.github.io/angular-openlayers-directive/examples/063-markers-properties-example.html

Markers not visible, otherwise seems to work as intended:
http://tombatossals.github.io/angular-openlayers-directive/examples/064-markers-render-html-inside-labels-example.html

Marker not visible:
http://tombatossals.github.io/angular-openlayers-directive/examples/065-markers-static-image-layer-example.html

**Comment by tombatossals** [comment]
Hi @zzats, you're totally right, the new library version was not uploaded to the "gh-pages" branch, which is the one used on github public pages.

Now it seems to work well again.

Thanks for reporting!

**Comment by zzats** [comment]
Thank you @tombatossals for the quick fix! Still a follow-up: the examples still have issues with static images and markers with pixel projection

http://tombatossals.github.io/angular-openlayers-directive/examples/065-markers-static-image-layer-example.html

**Comment by tombatossals** [comment]
Totally right, it was a bug with the new features I'm implementing of drawing paths that affected the markers in the pixel projection.

Now it's working, thanks!!!
