### ISSUE TITLE
How to use Swiss Geo Admin API with angular-openlayers-directive

### ISSUE THREAD

**Issue by darjiyogen** [tombatossals/angular-openlayers-directive#324]
Hello,

I've used OpenLayers 3 and angular-openlayers-directive as map project but as soon as I added reference for http://api3.geo.admin.ch/ Swiss Geo services in existing project, it breaks map and styles also.

Is there any suggestions or solutions to workaround this issue?

**Comment by juristr** [comment]
@darjiyogen Hi, I'm sorry but I didn't work with the swiss geoadmin tools yet. Also we'd have to know which kind of errors you're getting and what exactly breaks. thx
