### ISSUE TITLE
Multiple maps - overlay problem

### ISSUE THREAD

**Issue by oiacrasec** [tombatossals/angular-openlayers-directive#328]
Hello guys, i need help to open multiple maps in tabs. I already created the maps but there is a problem... when 2 or more maps are open and i click over one position the popover go to the first map opened

I was looking the HTML and when a popover is opened it creates a div.ol-overlay-container inside div.ol-overlaycontainer-stopevent. Is there a way to especify the container or one way to get it working?

**Comment by oiacrasec** [comment]
How can i specify the "target" map?

**Comment by oiacrasec** [comment]
Solved, i just had to pass the ID to getMap()

example:
```
olData.getMap('MY_ID').then(function (nativeOl3Map) {

}
```

**Comment by ablaye** [comment]
Hello I found the solution [here](https://github.com/tombatossals/angular-openlayers-directive/issues/342)

**Comment by juristr** [comment]
Thanks @ablaye. I'm closing this issue as I assume your suggestion solved it. thanks a lot!
