### ISSUE TITLE
How to disable click event on vectors layer when dragging maps

### ISSUE THREAD

**Issue by chiconguyen2601** [tombatossals/angular-openlayers-directive#33]
My maps use several GeoJSON layers, i want disable click event on these when dragging maps?
Please help me...tks so much!

**Comment by tombatossals** [comment]
Hi @chiconguyen2601, are you interested in disabled events in some specific GeoJSON layers or in all GeoJSON layers?

With the new version (0.0.3) of the library  you can disable layer events with the defaults object:
```
defaults: {
    events: {
        layers: []
    }
}
```

Cheers
