### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by cramatt** [tombatossals/angular-openlayers-directive#334]
I've forked the repo with the intention of doing a PR but I can not get the tests to run. After running `npm install`, I get the following error when running `grunt test:unit

```
04 11 2016 23:37:26.190:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
04 11 2016 23:37:26.193:INFO [launcher]: Starting browser PhantomJS
04 11 2016 23:37:26.290:ERROR [launcher]: Cannot start PhantomJS

04 11 2016 23:37:26.294:INFO [launcher]: Trying to start PhantomJS again (1/2).
04 11 2016 23:37:26.384:ERROR [launcher]: Cannot start PhantomJS

04 11 2016 23:37:26.386:INFO [launcher]: Trying to start PhantomJS again (2/2).
04 11 2016 23:37:26.482:ERROR [launcher]: Cannot start PhantomJS

04 11 2016 23:37:26.484:ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
```

node version: v4.6.0
npm version: 3.10.8
Mac os Sierra 10.12

**Comment by cramatt** [comment]
So fixed the phantom issue thanks to this, https://github.com/karma-runner/karma-phantomjs-launcher/issues/138#issuecomment-258373766, upgrading to recent phantom worked. 

But now the tests are failing because of another error: 

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: angular
  at /Users/mmiller/Sites/forks/angular-openlayers-directive/dist/angular-openlayers-directive.js:16
```

My question is are the tests still being maintained and do I need to get them passing for a new PR? 

Thanks, 
Matt

**Comment by cramatt** [comment]
Gah - silly me I forgot to run bower install. Although a few things. 

1. still getting failed tests via phantom
2. the contributing docs don't mention running bower install for testing (although its pretty standard but it does mention npm install)
3. the output from running `grunt` is much shorter than what is documented in contributing... its only logging that it created a min file, but nothing else... ?

**Comment by juristr** [comment]
:smiley:
