### ISSUE TITLE
Documentation of olData and olHelper

### ISSUE THREAD

**Issue by ablaye** [tombatossals/angular-openlayers-directive#339]
Hello, 
Where to find documentation of olData object and olHelper?

Thanks

**Comment by juristr** [comment]
Hey, ya I know 😞. Unable to keep up with docs. I'd suggest taking a look [at the unit tests](https://github.com/tombatossals/angular-openlayers-directive/tree/master/test/unit).
For instance [here](https://github.com/tombatossals/angular-openlayers-directive/blob/master/test/unit/openlayersSpec.js#L35) for a `olData` example.

Something should be as well here:

- http://tombatossals.github.io/angular-openlayers-directive/#/
- https://github.com/tombatossals/angular-openlayers-directive/tree/master/doc

Hope this helps.
