### ISSUE TITLE
Possible to use center url hash with ui-router?

### ISSUE THREAD

**Issue by averas** [tombatossals/angular-openlayers-directive#35]
Angular itself does not have a problem with the center url hash parameter, however, when using ui-router an update to the URL (including the query parameters) will cause a state transition, which re-renders the views. Is there any good way to avoid this?

**Comment by tombatossals** [comment]
Yess, I had the same problem developing the public page of the directive. Look at this example working with url-hash:

http://tombatossals.github.io/angular-openlayers-directive/#/first/center-url-hash?c=-18.6379:49.1930:5

The trick is related with angular router, which reloads the controller if there is a change on the location.search parameters. You have to set the parameter "reloadOnSearch" to "false".

Source code of the example:
https://github.com/tombatossals/angular-openlayers-directive/blob/gh-pages/js/routes/main.js
