### ISSUE TITLE
Create layer dinamically

### ISSUE THREAD

**Issue by evisms** [tombatossals/angular-openlayers-directive#354]
Hi,

Is it possible to create a layer dinamically in the controller and add it to the rest layers? I can't create it when the app starts up because I don't have the source until the user selects some parameters, Is it possible? Perhaps through the Openlayers native code?
olData.getMap().then(function(map) {			   
		    var layers = map.getLayers();...

//something as layers.push(new layer...)

Thanks in advance

**Comment by earosb** [comment]
You can create a vector and added to the map

```javascript
olData.getMap().then( function ( map ) {
  var vectorLayer = new ol.layer.Vector( {
    source: new ol.source.Vector( {
      url: 'https://openlayers.org/en/v4.0.1/examples/data/geojson/countries.geojson',
      format: new ol.format.GeoJSON()
    } ),
    style: new ol.style.Style( {
      fill: new ol.style.Fill( {
        color: 'rgba(255, 255, 255, 0.6)'
      } ),
      stroke: new ol.style.Stroke( {
        color: '#319FD3',
        width: 1
      } )
    } )
  } );
  vectorLayer.setMap( map );
}
```

**Comment by juristr** [comment]
@earosb Thx for jumping in :clap:. @evisms if this solves your issue please make sure to close it afterwards :smiley:

**Comment by evisms** [comment]
That solved it! Thanks a lot ;)
