### ISSUE TITLE
Setting center in defaults object has no effect

### ISSUE THREAD

**Issue by Toilal** [tombatossals/angular-openlayers-directive#356]
Defining `center` property in `defaults` attribute seems to have no effect

After some debuging, i've found that [setDefaults(scope) method](https://github.com/tombatossals/angular-openlayers-directive/blob/master/src/services/olMapDefaults.js#L100) doesn't read the `center` property of `userDefaults` object to merge the directive defaults with user defaults.

**Comment by juristr** [comment]
@Toilal I see. could you may submit a PR that fixes this problem with an according test case?

**Comment by juristr** [comment]
Also, you could maybe try setting it through the `ol-center` property:

```html
<openlayers ol-center="vm.center">
   ...
</openlayers>
```
and `center` could be something like this:

```javascript
vm.center = {
    autodiscover: false, // some browsers are making problems
    lat: 5886269.5,
    lon: 1272520,
    zoom: 10,
    projection: 'EPSG:3857',
    bounds: []
};
```

**Comment by juristr** [comment]
Please re-open the issue if it persists.
