### ISSUE TITLE
Is it possible to use ServerVector as source of a vector layer?

### ISSUE THREAD

**Issue by vkasala** [tombatossals/angular-openlayers-directive#36]
Hello,

I would like to know, if it is possible to use ServerVector source in vector layer with custom angularjs http function? And also synchronize the state of loaded data with some other controller?

Thanks.

**Comment by tombatossals** [comment]
Hi, I hink it could be easily added. Do yo have any ServerVector remote source which we can use to make an example? I have never used it.

And I suppose it could be used to sync another controller variables, Can you explain your idea so we can make a simple demo to illustrate it?

**Comment by vkasala** [comment]
Right now I do now have a remote source. You can you multiple static json files to simulate different data. 

Use case:

I would like to have ServerVector source which will load GeoJSON from specific REST URL with bounding box Strategy. I would like to use $http or $resource service. And I would like to have layout with two panels. One panel will be the sidebar and other ol map with ServerVector. I would like to sync data in map with the sidebar panel, where loaded features will be listed.

Thanks a lot.

**Comment by tombatossals** [comment]
It can be added easily, I have never worked with ServerVector and I don't know how they work. If you provide me the static json file to simulate the data I can code the layer functionality.

Cheers.

**Comment by kratosmat** [comment]
Hi all,
I am interested on using wfs source vector.

I am listing my ol3 code to handle a wfs source:

// Source retrieving WFS data in GeoJSON format using JSONP technique
var vectorSourceJsonp = new ol.source.ServerVector({
	format: new ol.format.GeoJSON(),	
	loader: function(extent, resolution, projection) {
		var url = 'http://localhost:8090/geoserver/REWARD/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=REWARD:capevents&' 
		+ 'srsName=EPSG:3857&bbox=' + extent.join(',') + ',EPSG:3857&outputFormat=text/javascript&format_options=callback:loadFeatures';

		$.ajax({url: url, dataType: 'jsonp'});
	}
});

// Executed when data is loaded by the $.ajax method.
var loadFeatures = function(response) {
	vectorSourceJsonp.addFeatures(vectorSourceJsonp.readFeatures(response));
};

// Vector layer
var vector = new ol.layer.Vector({
	source: vectorSourceJsonp,
/*
	style: new ol.style.Style({
  		fill: new ol.style.Fill({
    			color: 'blue'
  		}),
  		stroke: new ol.style.Stroke({
    			color: 'olive',
    			width: 1
  		})
	})
*/
});

after that you only have to add this layer to ol.Map objet.

Do you think it is possible to develop angular directive to manage it?

Bye,
Matteo.

**Comment by kratosmat** [comment]
Hi all,
I have solved, I have added a layer type called JSONP that manage ajax call through $http angularjs module.

If someone is interested I will post here the code or I could add it into repository.

Bye,
Matteo.

**Comment by vkasala** [comment]
Hi Matteo,

I would really appreciate your code. Thanks a lot.

Bye,
Viliam

**Comment by kratosmat** [comment]
I have submitted a pull request.
I am not expert of git process, so tell me if I have to do more steps.

Bye,
Matteo.
