### ISSUE TITLE
Option doubleClickZoom :false doesn't exist

### ISSUE THREAD

**Issue by tatianass** [tombatossals/angular-openlayers-directive#362]
I am trying to remove the zoom when double clicking. Like [this ](http://gis.stackexchange.com/questions/127047/disable-doubleclick-zooming-in-openlayers-3)post. But when I did: 'interactions:{doubleClickZoom:'false'}'. It didn't work, so I looked around in the directive and couldn't find this option. Could you add it please?

**Comment by juristr** [comment]
Hey, it actually should already work by passing in a proper configuration object on the `ol-defaults` property.

```html
<openlayers ol-defaults="vm.mapConfig">
   ...
</openlayers>
```

And in your controller you have to have something like this:

```javascript
function MapDirectiveController() {
    var vm = this;
    vm.mapConfig = {
      ...
      interactions: {
         doubleClickZoom: false
      }
    } 
}
```

That works for me. Feel free to re-open the issue if it still doesn't work for you :smile:

**Comment by tatianass** [comment]
Still not working:
`angular.extend(self, {
            center: coordenadaBrasil,
            marcadoresDelegacias: marcadoresDelegacias,
            layers: [estadosTopoJSON, mapBox],
            defaults: {
                events: {
                    layers: [ 'mousemove', 'click' , 'dblclick'],
                },
                interactions: {
                  mouseWheelZoom: 'true',
                  doubleClickZoom : 'false'
                },
                view: {
                    maxZoom: 20,
                    minZoom: 4
                }
            }
        });`

`ol-defaults="correicoesCtrl.defaults"`

**Comment by tatianass** [comment]
```javascript
angular.extend(self, {
            center: ...,
            markers: ...,
            layers: [..., mapBox],
            defaults: {
                events: {
                    layers: [ 'mousemove', 'click' , 'dblclick'],
                },
                interactions: {
                  mouseWheelZoom: 'true',
                  doubleClickZoom : 'false'
                },
                view: {
                    maxZoom: 20,
                    minZoom: 4
                }
            }
        });
```
```javascript
<openlayers ...  ol-defaults="correicoesCtrl.defaults" ...>
	...
</openlayers>
```

**Comment by tatianass** [comment]
Open #362

**Comment by juristr** [comment]
Can you try to pass `false` as a boolean rather than a string?

**Comment by tatianass** [comment]
Yeap, that did the trick, Thank you :)
