### ISSUE TITLE
Support newer versions of OL?

### ISSUE THREAD

**Issue by chander** [tombatossals/angular-openlayers-directive#370]
Right now it looks like the code uses some pretty old stuff - for example using ol.animation (rather than view animations) and map.unByKey (which is now ol.Observable.unByKey) - just to name a couple.  Any plans to upgrade/update to support the current OL version(s) ?

**Comment by juristr** [comment]
Hi, we currently use it with openlayers v3.13.1, so I can confirm it works with that version. To which version did you want it to be upgraded. And could you eventually submit a PR for it? That'd be great as I'm currently short on time :smile:. Obviously I could help guide you if needed.

Let me know

**Comment by juristr** [comment]
See #383

**Comment by juristr** [comment]
Version 2.0.0 with openlayers v4 has just been released
