### ISSUE TITLE
package.json and bower.json specify different versions of OpenLayers

### ISSUE THREAD

**Issue by NoisyFlowers** [tombatossals/angular-openlayers-directive#373]
package.json specifies OpenLayers 3.18.1 as a dependency. bower.json specifies 3.16.0. I am installing from bower, but I need to use OL features that don't exist until 3.18 (specifically, ol.format.ogc.filter.intersects). Is there any reason that bower.json requires an earlier version? If not, can this be bumped up? 

Thanks!

**Comment by juristr** [comment]
Should be ok once #383 gets merged
