### ISSUE TITLE
Arcgis map is not working till openlayers 3.17.0

### ISSUE THREAD

**Issue by mfilotto** [tombatossals/angular-openlayers-directive#385]
My map displayed with WMS Argics Tiles is not working anymore.
This is solved by https://github.com/openlayers/openlayers/issues/5430 in version 3.17.0
(STYLES parameter should be sent with = : `&STYLES=&`)

The error can be seen here : http://openlayers.org/en/v3.16.0/examples/wms-image.html?q=wms
And solved here : http://openlayers.org/en/v3.17.0/examples/wms-image.html?q=wms

So it would be great to upgrade openlayers to version 3.17.0 at least

**Comment by mfilotto** [comment]
#383

**Comment by juristr** [comment]
Ok, thx for reporting this. I'll take a look at #383 as soon as I can. so to avoid duplicates, I'm closing this one. thx again
