### ISSUE TITLE
Error with ng-repeat and ol-marker-properties

### ISSUE THREAD

**Issue by samtux** [tombatossals/angular-openlayers-directive#40]
To represent a list of markers, I am using the following:

```html
<ol-marker ng-repeat="marker in markers" ol-marker-properties="marker"></ol-marker>
```

However the representation of the markers are shown as two blue circuferencias without the blue icon marker.

The correct representation was as follows:

```html
<ol-marker ng-repeat="marker in markers" lat="marker.lat" lon="marker.lon" message="{{marker.label.message}}"></ol-marker>
```

But do not take the properties of the label as 'show' and 'showOnMouseOver'.

**Comment by tombatossals** [comment]
Hi @samtux,
that's a weird behaviour, in this examle it seems to work fine:

http://tombatossals.github.io/angular-openlayers-directive/examples/061-markers-add-remove-example.html

Could you make a jsfiddle showing the problem? You could use [this jsfiddle](http://jsfiddle.net/tombatossals/v3b0p54h/) as a starting point.

**Comment by samtux** [comment]
Thanks for your time @tombatossals. It was a mistake to change the  OpenLayers directives. Here the link showing the markers correctly:

http://jsfiddle.net/samtux/v3b0p54h/20/
