### ISSUE TITLE
Too many map points(ol-marker) lead to a slow down

### ISSUE THREAD

**Issue by abelleeye** [tombatossals/angular-openlayers-directive#405]
When I use ol-marker ng-repeat so much elements.
Map will can not move and so slow, but it can zoom.
I hope I can get some help to resolve this trouble.

**Comment by oiacrasec** [comment]
Hello, same problem here.
I think the problem is caused because there is too many html elements inside dom
![image](https://user-images.githubusercontent.com/6432703/65878477-89d23400-e364-11e9-84fb-f88879f455cc.png)

Im trying to push to layers array the native map.addLayer with no success yet.

**Comment by oiacrasec** [comment]
I refatored my code to use pure OpenLayers lib and now is working like a charm. 
I you have a lot of markers / layers the directive is going to create a lot of information inside the DOM.
It will slow down the performance.

**Comment by abelleeye** [comment]
I used cluster future of OpenLayers, It solved my problem.
