### ISSUE TITLE
3D cesium

### ISSUE THREAD

**Issue by kratosmat** [tombatossals/angular-openlayers-directive#44]
Hi all,
Are you interested on 3D capabilities provided by ol Cesium?

Now I am extending your directive in order to add 3D capabilities.

**Comment by ndufrane** [comment]
Hi,
I would be great to have some 3d capabilities indeed !

**Comment by tombatossals** [comment]
Hi @kratosmat.

Yes of course, please send a PR with the modifications.

**Comment by tombatossals** [comment]
Hi, I'm going to close this old issue. Please feel free to send your PR whenever you like

**Comment by garymazz** [comment]
Was the PR merged  ? I didn't see it.
