### ISSUE TITLE
Getting events propagation to work for static image map, need some help

### ISSUE THREAD

**Issue by style-x7** [tombatossals/angular-openlayers-directive#45]
Hi all,

1st, thanks for the wonderful directive :+1: 

I'm trying to tweak the example http://tombatossals.github.io/angular-openlayers-directive/examples/080-events-propagation-example.html to work for static image map but no event is firing ("openlayers.map.singleclick").

Tried also to change "openlayers.map.singleclick" to "openlayers.layers.singleclick" (since my static image is on a layer) but still getting no event.

Can shed some light on this?

**Comment by tombatossals** [comment]
Hi @style-x7 , you're totally right, the events functionality is not finished yet. I have added the pixel projection (static image layer) propagation of events, so you can now listen for "pointermove" or "singleclick" in an static image. I have added this example too:

http://tombatossals.github.io/angular-openlayers-directive/examples/083-events-static-image-layer-example.html

**Comment by style-x7** [comment]
Hi @tombatossals,

You're so cool :) I didn't expect to get response and a fix so fast!

I've updated to the master branch and verified the fix, all's good.
