### ISSUE TITLE
Marker icon can't be customized

### ISSUE THREAD

**Issue by nbiton** [tombatossals/angular-openlayers-directive#47]
The marker style is hardcoded to the olMarker directive, and it isn't overriden if you set a custom one to the defaults set to the map.

**Comment by tombatossals** [comment]
Hi @nbiton 
Yesss, I'm using it this way but the code can be easily extended to support custom icons, you're right that this could be a good functionality.

I'm going to add it and make an example of use, tell you something later.

**Comment by nbiton** [comment]
This did it for me. 
With it, I can define the styles in the default provided to the openlayers directive like so:
```
$scope.defaults = {
    styles: {
        marker: {
          image: new ol.style.Icon({
            anchor: [0.5, 1],
            anchorXUnits: 'fraction',
            anchorYUnits: 'fraction',
            opacity: 0.90,
            src: 'img/marker.svg'
          })
        }
      }
};
```
