### ISSUE TITLE
Styling dynamic marker

### ISSUE THREAD

**Issue by signix** [tombatossals/angular-openlayers-directive#49]
The dynamic style for marker does not allow to change icon. Is it expected ?
What is wrong with this fiddle : http://jsfiddle.net/xxjq7o1x/1/ ?
Thanks

**Comment by tajikase** [comment]
Can we specify marker image as a part of ol-marker-properties?

**Comment by tombatossals** [comment]
Hi @signix, it's better not to instance the ol.style.Icon object, pass only the properties and the directive will instance it for you. Take a look at this example:

http://tombatossals.github.io/angular-openlayers-directive/examples/067-marker-custom-icon-example.html

**Comment by signix** [comment]
Noticed.
Thank you very much for the example.
Nice job with this directive.

**Comment by tombatossals** [comment]
Hi @tajikase, yes you can specify the marker image as part of ol-marker-properties, and it will be watched so you can change the image url in the object and it will be changed in the map.

**Comment by tajikase** [comment]
I was able to change marker images according to your example. Thank you so much.
