### ISSUE TITLE
Style Multipoint GeoJson

### ISSUE THREAD

**Issue by andresramirezmiori** [tombatossals/angular-openlayers-directive#51]
When i tried to add styles to a multipoint geojson, the layer disappeared. i noted that on the dist directive at the createStyle function there is not a case for image or something like ol.style.Circle

**Comment by juristr** [comment]
@andresramirezmiori Is this issue still valid? There are a couple of other closed issues and PRs referencing this one. So I assume it's solved. Can you confirm?
