### ISSUE TITLE
Source does not allow null crossOrigin

### ISSUE THREAD

**Issue by myspivey** [tombatossals/angular-openlayers-directive#52]
Currently Open Layers supports null as a valid value for crossorigin. Currently if you attempt to pass null (which is the default value in ol) it executes the following: crossOrigin: source.crossOrigin ? source.crossOrigin : 'anonymous'.

Since this sees source.crossOrigin as null, it then applies anonymous instead which is not the desired behavior. This breaks any server that does not have CORS enabled.

**Comment by philnug** [comment]
I am running into this as well.

**Comment by sjdixon** [comment]
As am I.

**Comment by mikostn** [comment]
This probbolbly applies to ImageWMS, TileWMS and TileVector

**Comment by sjdixon** [comment]
OK, looks like anyone who is having this issue can get rid of it by using the development branch.

in bower.json: 
>"dependencies": {
>    "angular-openlayers-directive": "https://github.com/tombatossals/angular-openlayers-directive.git#master"
>}

**Comment by mikostn** [comment]
@sjdixon - except "TileVector", I'll try to fix and PR this issue
