### ISSUE TITLE
Kml click events

### ISSUE THREAD

**Issue by plattdl** [tombatossals/angular-openlayers-directive#53]
I have been looking at the click event examples and trying to adapt them to KML layers instead of geojson. Had little luck and was wondering if this was possible.

Thanks

**Comment by tombatossals** [comment]
Could you post a KML example file? I will try to integrate it, it shouldn't be difficult.

**Comment by plattdl** [comment]
Sure! Here is a simple states example.

https://www.dropbox.com/s/zek9vtkp6k7fq0c/states.kml?dl=0

Thanks again

**Comment by tombatossals** [comment]
Hi @plattdl,
now it's possible to manage KML layer events. I have used your KML to create a very simple example of use:

http://tombatossals.github.io/angular-openlayers-directive/examples/085-events-kml-example.html

Thanks.
