### ISSUE TITLE
Draw feature for static map

### ISSUE THREAD

**Issue by style-x7** [tombatossals/angular-openlayers-directive#54]
Hi all,

I'm hoping to draw line between markers on static map.

Any idea I can achieve that using angular-openlayers-directive? Or how can I extend the directive?

Thanks in advance.

**Comment by penance316** [comment]
I am also interested in this as i would like to annotate building and such on the map using openlayers polygons and lines. I assume i need to extend the directive.

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).

**Comment by AnasELMALEKI** [comment]
i neec this too, is there any solution yet ?
