### ISSUE TITLE
Tile layer with custom source subclasses from TileImage

### ISSUE THREAD

**Issue by vkasala** [tombatossals/angular-openlayers-directive#55]
Hello,

is it possible to add custom tile layer with my own source subclass which is in seperate file?

thanks

**Comment by juristr** [comment]
I'm doing some housekeeping and closing the issue since it's quite old. Please feel free to re-open it if it still persists. Also maybe try to upgrade to the [latest version as it might fix it for you](https://github.com/tombatossals/angular-openlayers-directive/releases).
