### ISSUE TITLE
Add dynamically layers with code from Controller

### ISSUE THREAD

**Issue by vkasala** [tombatossals/angular-openlayers-directive#56]
Hi,

is there a way how to dynamically add layers from Controller? e.g. Is it a good way to add layers from Controller that has injected olData service?

Thanks.

**Comment by tombatossals** [comment]
Hi, you can add dinamically the layers using the template. For example, you could iterate a layers object with "ng-repeat" in the template, or you can conditionally add/remove a layer with "ng-if".

Supose you have an object named "kmldata" with all the layer properties. You could show it/remove it in your map with this template:

```
<openlayers ol-center="europe" custom-layers="true" height="400px">
    <ol-layer ol-layer-properties="kmldata" ng-if="kmldata"></ol-layer>
</openlayers>
```


Take a look at this example too: http://tombatossals.github.io/angular-openlayers-directive/#/layers/layer-multiple

**Comment by vkasala** [comment]
Hi,

I need to add specific layer object, because it this layer object has specific source, which extend TileImage. I also need dynamically add geojson into map, than some marked. I need it to do it with javascript code from controller which fetches data and then add then to map. If user refetch data, then I need erase that  dynamic layer and add new layer with this data.

Is this possible as I have suggested before? I also needs to pass resoulutions parameter into View object. I have't found solution for this.

```javascript
var map = new ol.Map({
        target: 'map',
        layers: [
            new ol.layer.Tile({
                title: 'Base Map',
                type: 'base',
                visible: true,
                source: new ol.source.MyOwnMap({
                    layer: 'base'
                }),
                /* Do not know why */
                extent : [33554432, 33554432, 251658240, 251658240]
            }),
        ],
        view: new ol.View({
            projection: ol.source.MyOwnMap.getProjection(),
            resolutions: ol.source.MyOwnMap.RESOLUTIONS,
            extent: ol.source.MyOwnMap.VIEW_EXTENT,
            center: [0,0],
            zoom: 0
        })
    });```
