### ISSUE TITLE
Add support for Group layers object

### ISSUE THREAD

**Issue by vkasala** [tombatossals/angular-openlayers-directive#59]
Hello,

I would like to ask, if it is possible to add group layers into Groups ? I have managed to make workaround for it, but I am initializing map layers in my special directive and in their link function. If there was this feature, than it would work nice with https://github.com/walkermatt/ol3-layerswitcher. This uses 2 Group layers as default, one for Base layers (only one can be activated) and OverLayers(json, topografic)...

I think maybe it would be good, if I angular-ol would create two Group layers by default and then add other layers into this 2 groups according to specified parameter.

Thanks for response.

Viliam Kasala

**Comment by juristr** [comment]
HI @vkasala . this has been implemented by @lewisjared in #181
