### ISSUE TITLE
Changing a style function of a layer list does not invoke the watch function.

### ISSUE THREAD

**Issue by fyaa** [tombatossals/angular-openlayers-directive#66]
This [jsFiddle example] (http://jsfiddle.net/fyaa/mx7nu3j3/) shows the problem that changing a style function does not affect the layer. The $watch is not invoked here and nothing changes.

However, if you first click on the "change style" button and then make the layer invisible and visible again, you can see the effect.

**Comment by tombatossals** [comment]
Good point @fyaa, I have solved this issue, you can see it working in this example:

http://tombatossals.github.io/angular-openlayers-directive/examples/051-layer-geojson-change-style-with-function-example.html

Thanks
