### ISSUE TITLE
map will not be rendered in an angular ui modal or tab

### ISSUE THREAD

**Issue by harpandrew** [tombatossals/angular-openlayers-directive#70]
If the directive is used in a modal window or in a tab the map does not show up. The error message is the following:
Uncaught TypeError: Cannot read property 'time' of null

**Comment by tombatossals** [comment]
Hi @harpandrew , Could you provide a jsfiddle showing this behaviour?

**Comment by compso** [comment]
Hi @tombatossals I have made a codepen that shows the issue :

http://codepen.io/compso/pen/WvWOGv

I think it is because the map object needs to created after the modal dialog is created.

**Comment by compso** [comment]
Found a solution:
http://codepen.io/compso/pen/WvWOGv

Works by waiting on the "rendered" promise of the modal dialog, and setting a scope variable to true, then linking this to the ng-if of the openlayers element.

**Comment by juristr** [comment]
@compso I'm closing this issue now as I think it's resolved :smile:. Reopen it when necessary.
