### ISSUE TITLE
Styling a GeoJSON Point with ol.style.Circle

### ISSUE THREAD

**Issue by dan-hook** [tombatossals/angular-openlayers-directive#74]
In the style section, is there a way to set the image style attribute to be an ol.style.Circle?

**Comment by dan-hook** [comment]
Related issue: https://github.com/tombatossals/angular-openlayers-directive/issues/51

**Comment by dan-hook** [comment]
I've figured out how to do it.  Hopefully I'll have a pull request that provides this functionality ready next week.

**Comment by tombatossals** [comment]
Hi @dan-hook, it would be great if you could send a PR with this functionality. Please tell me if I could help
