### ISSUE TITLE
Detecting click on a marker

### ISSUE THREAD

**Issue by ukjbrown** [tombatossals/angular-openlayers-directive#76]
How do you setup a listener to handle a click on a marker... Can't seem to find an example or work it out by tracing through the code. On the OpenLayers site this would require access to the map object to then get the feature at the pixel, but how would you get access to the map when handling the "openlayers.map.singleclick" event in a controller?

**Comment by nbiton** [comment]
Check out the example with the "showOnMarkerOver" property:
http://tombatossals.github.io/angular-openlayers-directive/examples/063-markers-properties-example.html

You can use another property called "showOnMarkerClick"  that works exactly the same,  but with mouse clicks. 
It might not be exactly what you need,  so you can look at the olMarker directive to see how the two of these are implemented, and you could extend it to capture clicks for other purposes.

**Comment by ukjbrown** [comment]
I need to detect a click on the marker and do "something", not simply have it show a popup though... This must be a standard requirement. When a marker is clicked I need some type of event to bubble up so that I can find out which marker was clicked and therefore extract properties from the marker.

**Comment by nbiton** [comment]
Yeah, it seemed that you might have a different use case, that's why I suggested you look the olMarker directive source code. I believe it shouldn't be too complicated to add an attribute to the directive which allows assigning a general handler for clicks.

**Comment by ukjbrown** [comment]
It's not so easy to simply follow olMarker to work out what to do here. There's so little documentation for what things do in both the directive and openlayers 3 itself. In the olMapDefaults there is an events dictionary that has an array called "markers". This would suggest there is already some type of management of marker events... What are these used for? Is there a way to define a $scope.$on() for these events? What are the events name? There seems to be this magical "openlayers.*.*" event structure that has zero documentation other than the examples... Is there a known way to setup these listeners without guessing the structure?

**Comment by nbiton** [comment]
I'm not sure what do you mean about the event structure, but I can highlight these lines which are responsible of detecting if a marker has been clicked, this is taken from the event handler called "showLabelOnEvent" in marker.js, starting from line 129:

```
var pixel = map.getEventPixel(evt);
var feature = map.forEachFeatureAtPixel(pixel, function(feature) {
  return feature;
});

if (feature === marker) {
  // This is the marker currently under the mouse cursor
}
```

These lines can be refactored out of the event handler, which is specific for showing and hiding the marker label, to a general mouse event handler, which can trigger a click handler within the "properties" scope variable, if the click handler was set.

**Comment by myspivey** [comment]
I had the same issue, I added this to olMarker and it worked for my use case. I added a source property be able to include a data object from an ng-repeat that builds the marker. You will have to add the cursor icon manually.

```javascript
map.on('singleclick', function(e) {
                  var feature = map.forEachFeatureAtPixel(e.pixel, function(feature) {
                    return feature;
                  });

                  if (feature === marker) {
                    scope.$emit('openlayers.map.markerclick', {
                      data: scope.source,
                      lat: scope.lat,
                      lon: scope.lon
                    });
                  }
                });
```

**Comment by ukjbrown** [comment]
Thanks @myspivey . Did you manage to extend the directive or did you have to create a copy and amend, I'd like to extend but for some reason the developer opted not to store the 'marker' object in scope so I can't see a way to do the (feature == marker) check as marker is not accessible outside that function in the directive.

**Comment by myspivey** [comment]
I modified this on a local copy. I have had to make several changes for our particular use cases where extension is not really an option so did the same here. My solution though would be a pretty easy pull request to implement so it was built into the directive if you want to tackle that.

**Comment by tombatossals** [comment]
Hi guys, you're right, that functionality is not coded in the directive yet. I will continue implementing it when have some more spare time, any help would be appreciated.

**Comment by carpiediem** [comment]
It looks like the suggestions above will work for what I'm trying to do, but if there's any way to get this to work by default with the ng-click attribute of an ol-marker element, that would seem like the most flexible solution.

**Comment by nbiton** [comment]
It's done, look at the PR which gives you the option to set a click handler on the marker properties.

**Comment by carpiediem** [comment]
Thanks!

**Comment by guaxy** [comment]
i need help here look this code
index.html
<openlayers ol-center="center" width="100%" height="94vh" ol-defaults="defaults" >
			<ol-marker ng-repeat="marker in markers"  ol-marker-properties="marker" ></ol-marker>
		</openlayers>
app.js

.controller("MapController", [ '$scope', '$http', 'olData', function ($scope, $http, olData) {
    var markers = [];

    function init(){
        $http.get('/utils/tiendas/status')
        .success(function (response){
            $scope.tiendas = response;
            initMapa(response);
        })
        .error(function (err){
            console.error(err);
            $scope.tiendas = [];
            initMapa();
        });
    }

    function initMapa(tiendas){
    	markers = tiendas;
    }
   

   $scope.marker = [
  {
    "name": "London",
    "lat": 51.505,
    "lon": -0.09,
     onClick: function (event, properties) {
    console.log(this); // ol.Feature instance
    console.log(properties); // === $scope.marker
  }
  },
  {
    "name": "Bath",
    "lat": 51.375,
    "lon": -2.35,
     onClick: function (event, properties) {
    console.log(this); // ol.Feature instance
    console.log(properties); // === $scope.marker
  }
  }
  ];
   	angular.extend($scope, {
	        center: {
	            lat: 20.679,
	            lon: -103.386,
	            zoom: 2
	        },
	        controls: [
	            { name: 'zoom', active: true },
	        ],
	        markers : $scope.marker || [],
	});
why onClick event in properties not working :c

**Comment by MrGorki** [comment]
+1 Unfortunately I couldn't get it working too.

**Comment by guaxy** [comment]
I did my friend, what is your trouble @MrGorki ?

**Comment by danielrvt** [comment]
+1 this is not working

**Comment by jmeade11** [comment]
The only way I could get it to work is to:

Have a label property defined for the marker.
Have the show property of the label set to false.
Have some transcluded content in the marker.

If any of the above are not set, it seems to not work.

So for example:

    finisterre: {
          lat: 42.907800500000000000,
          lon: -9.265031499999964000,
          label: {
            show: false,
          },
          onClick: function (event, properties) {
            console.log(properties); // === $scope.marker
            alert('lat: '+ properties.lat+', '+'lon: '+properties.lon);
          }
    }

And in the HTML, I used:

    <ol-marker ol-marker-properties="finisterre" class="hidden">Finisterre</ol-marker>

**Comment by manpe** [comment]
Hello,

I wonder if anyone found a solution to have onClick event fire when the condition "Have the show property of the label object set to false" is not fulfilled?

Indeed it works well with show: false but for a use case where you want to display some name on your markers (vehicles on a map for example) and then click on the marker to show a different marker layout or go to a different page ... it doesn't work.

Thanks in advance!

**Comment by manpe** [comment]
Waiting for better days I went for this, that works but not sure how slower this is over the onClick marker method:

```javascript
map.on('singleclick', function(e) {
    var feature = map.forEachFeatureAtPixel(e.pixel, function(feature) {
	return feature;
    });
    if(feature && feature.n.marker) {
        feature.n.marker.label.message = "CLICKED!"; // Do something smarter here ...
    }
});
```

It works whether label show property is true or false.

**Comment by notph** [comment]
Hi,

Could you explain where do you put your code? I still get an error that map is not definied.

Thanks :)

**Comment by polesapart** [comment]
The proposed solution doesn't cover all cases. Besides, IMHO the angular way would be to forward the click event to the marker dom node and let ng-click handle it.

**Comment by notph** [comment]
@polesapart, any idea how to do that? I'm pretty beginner with angular and all that I tried don't work...

**Comment by polesapart** [comment]
@notph I have it almost working on https://github.com/polesapart/angular-openlayers-directive ;  I have a scenario where I'm getting two clicks instead of one but I'm unsure it's related as it doesn't happen on a minimum test case. If this gets stable enough (testers are more than welcome) I'll put a pull request.

**Comment by notph** [comment]
Thanks :) I'll have a look if I have any idea to fix it.

**Comment by polesapart** [comment]
It works for me™ as is. There are some caveats with marker deletion/recreation, but if you program simply update marker properties instead of deleting and recreating them (why I do that is a long history), you should be fine. You can delete a marker once it's really gone, but if for some reason you need to recreate it, don't do it in the same angular digest cycle and you'll be fine (use a $timeout closure on the latter).
