### ISSUE TITLE
Custom Tiles & PNG Projection

### ISSUE THREAD

**Issue by carpiediem** [tombatossals/angular-openlayers-directive#81]
I've been trying to use this directive to display some tiles that I made with the GDAL python script.  One part that I can't get right is the projection.  When I used the tiles in OpenLayers v2, markers were placed with pixel coordinates.  But in OpenLayers v3, I can only get the map to work in latitude and longitude.  Is there a way to set the projection I'd like?

I've posted some of my code [here](http://stackoverflow.com/questions/29316280/how-can-i-adapt-an-openlayers-v2-custom-tile-set-for-openlayers-v3), if that helps.

**Comment by carpiediem** [comment]
It looks like maybe I should be using the XYZ map type?  When I try that, the tiles aren't ever requested.

**Comment by tombatossals** [comment]
Hi @carpiediem, can I try mount the gdal server and make some tests by myself? Do you have any tutorial of how it can be installed&configured? 

If I can reproduce it I could take a look at it.

**Comment by carpiediem** [comment]
I followed [this blog post](http://blog.thematicmapping.org/2008/03/generating-map-tiles-with-gdal2tiles.html) while creating my map tiles.  When I searched for the URL just now, I found [this STack Exchange question](http://gis.stackexchange.com/questions/110566/problem-in-displaying-tile-images-using-openlayers3), which may lead me to the right solution (I haven't had the chance to try anything yet).

**Comment by ageblade** [comment]
I had success adding a (lat,lon) projected map generated by gdal-tiles only after adding support for XYZ in the switch case in createSource() method in the directive code.

**Comment by carpiediem** [comment]
I hadn't thought to check the switch case.  I don't have time to fiddle with my project at the moment, but I'll report back if I get it working.  It sounds like ageblade's edit would be a useful enhancement to the official directive, though.

**Comment by filipnovotny** [comment]
+1 to ageblade, I had the same problem and there is case to be added to the switch. In my case, I serve my own tiles in XYZ mode but I just tell angular-openlayers-directive that it's OSM and it works.

**Comment by ageblade** [comment]
I will post a PR with this add-on first thing tomorrow morning
