### ISSUE TITLE
Setting an overlay dynamically in an Ionic app

### ISSUE THREAD

**Issue by buecklers** [tombatossals/angular-openlayers-directive#83]
Hi there!

I'm creating an Ionic App and using the angular-openlayer-directive. So far it works but one problem still remains: On a click event on the map I fetch some properties of a feature and want to show them in an overlay. Depending on how I navigate (ui-route) to that view it works ... or not. A reload often helps. I even can see the overlay's html code in the page source but it is not visible.
To avoid race conditions, I added the html element in javascript not loading it from the html. I already spent a lot of time in that issue.
Does anybody have some experience in that frame work combination - angular, ionic, openlayers? I think you should.
Best and thanks in advance.
Thomas

**Comment by claustres** [comment]
Done something like this with angular, openlayers and phonegap. Started from this OL3 example http://openlayers.org/en/v3.4.0/examples/popup.html and it worked just fine. I plugged it with the directive like this (simplified version because my code is far more complicated):
```
...
olData.getMap().then( function(map) {
            // Create the overlaay
            var popup = new ol.Overlay({ element: $window.document.getElementById('popup') });
            map.addOverlay(this.popup);

            $scope.on('openlayers.map.pointerdown', function(event, data) {
              var feature = map.forEachFeatureAtPixel(data.event.pixel, function(feature) {
                  return feature;
              });
              // Show/Hide popup
              if ( feature ) { 
                  var html = '<h3 style="{text-align:center;}">popup</h3>';
                  $window.document.getElementById('popup-content').innerHTML = html;
                  popup.setPosition(data.coord);
              } else {
                  popup.setPosition(undefined);
                  return;
             }});
}
...
```

**Comment by jessemarple** [comment]
Hey @claustres - thank you for that snippet of code. Works like a dream!

**Comment by juristr** [comment]
Awesome guys :smile: . May I close this issue?

**Comment by claustres** [comment]
Yes, but before I might add a usefull tip, if you want to have some AnuglarJS code in your popup content then you will have to *compile* it like this:
```javascript
        var popupContent = $window.document.getElementById('popup-content');
        // Update popup content
        popupContent.innerHTML = html;
        // As we have an angular directive in generated HTML we need to compile it
        $compile(popupContent)($scope);
```

**Comment by juristr** [comment]
:+1:

**Comment by jacquesdev** [comment]
https://github.com/souly1/ng-walkthrough
