### ISSUE TITLE
Marker icons don't appear

### ISSUE THREAD

**Issue by mgbee8** [tombatossals/angular-openlayers-directive#91]
First of all this is wonderful, and much easier to work with than angular-google-maps.

I installed from bower today and setup a little demonstration page, following the markers add remove example.
I have three items in my markers array (below).
I assign them to $scope.markers
 Here is my html:

`<openlayers ol-center="usa" custom-layers="true" ol-markers="markers" height="700px">
  <ol-layer ol-layer-properties="bing"></ol-layer>
  <ol-marker ng-repeat="marker in markers" lat="marker.lat" lon="marker.lon" label="marker.label" ol-marker-properties="marker"></ol-marker>
</openlayers>`
 
When the page opens the 3 divs for the markers are present and labels and all present, however, no icon appears for the marker. Below are my scripts and links for the page.  
 
`<script src="bower_components/openlayers3/build/ol.js"></script>
  <script src="bower_components/angular/angular.min.js"></script>
  <script src="bower_components/angular-sanitize/angular-sanitize.min.js"></script>
  <script src="bower_components/angular-openlayers-directive/dist/angular-openlayers-directive.js"></script>
<link rel="stylesheet" href="bower_components/angular-openlayers-directive/css/angular-openlayers-directive.css" />
    <link rel="stylesheet" href="bower_components/openlayers3/build/ol.css">`

I am using BingMaps. Help!

 var markers =[
        {
          "lat": "32.722628",
          "lon": "-117.165331",
            "label": {
                "message": "Skills: This, that and the other <br /> Certifications: More stuff",
                "show": false,
                "showOnMouseOver": true
            }
        },
        {
          "lat": "36.831464",
          "lon": "-76.269871",
            "label": {
                "label":"Technician",
                "message": "Skills: This, that and the other <br /> Certifications: More stuff",
                "show": false,
                "showOnMouseOver": true
            }
        },
        {
          "lat": "30.44218",
          "lon": "-87.25585",
            "label": {
                "message": "Skills: This, that and the other <br /> Certifications: More stuff",
                "show": false,
                "showOnMouseOver": true
            }
        }
      ];

**Comment by mfilotto** [comment]
Hi Mickael,
Try to remove quotes around lat and lon values.
I made a jsbin of your case : first two markers apeare, the last one don't : http://jsbin.com/hudozo/2/
Bye
Math

**Comment by mgbee8** [comment]
Thanks, tried everything but that
