### ISSUE TITLE
Adding maxZoom for Bing maps

### ISSUE THREAD

**Issue by AbdelBa** [tombatossals/angular-openlayers-directive#94]
We could enhance the BingMaps with the maxZoom attribute which is used to display stretched tiles beyond max zoom level, as seen here : [openlayers doc](http://openlayers.org/en/v3.2.1/examples/bing-maps.html)

I tested it by editing the *angular-openlayers-directive.js* file. But it lacks flexibility.
```javascript
// line 1149
case 'BingMaps':
	if (!source.key) {
		$log.error('[AngularJS - Openlayers] - You need an API key to show the Bing Maps.');
		return;
	}

	oSource = new ol.source.BingMaps({
		maxZoom: 19, // <-- here
		key: source.key,
		imagerySet: source.imagerySet ? source.imagerySet : bingImagerySets[0]
	});

	break;
```

**Comment by juristr** [comment]
Submitted a PR #95 which should resolve this issue.

**Comment by juristr** [comment]
@AbdelBa PR #95 fixed this. You can now simply add a `maxZoom` property.

@tombatossals Guess this issue can then be closed.

**Comment by juristr** [comment]
@tombatossals I think you can close this issue, right @AbdelBa . My PR #95 should have solved this. :smile:

**Comment by AbdelBa** [comment]
Indeed ;)
